### ISSUE TITLE
Social Sticky Icons Improvements

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1061]
~should remove the CTA active conditions
~Add the position option ( Top or Bottom)

**Comment by nicholasgriffintn** [comment]
I've created a quick branch that does this, you can find it here:

https://github.com/nicholasgriffintn/accelerated-mobile-pages/tree/sticky-social

As soon as you release the dev branch for 0.9.60 I will pull it to that.

**Comment by pegazee** [comment]
@nicholasgriffintn  what about this situation http://take.ms/zPP6O. Sticky social is overriding the header logo.

**Comment by nicholasgriffintn** [comment]
Right, didn't notice that myself.

A good idea might to add "z-index: 9" to the css for the header logo and nav and then add "z-index: 8" to the sticky social css so that it floats underneath it and appears once you scroll the correct amount.

That would fix the issue, you could add a margin-top, however, that wouldn't work as you scroll.

**Comment by MohammedKaludi** [comment]
Social bar kept at the bottom, behind CTA bar using Z-index. Making Social Bar Stick on the top will be annoying for the users to read the content.

Closing the ticket.
