### ISSUE TITLE
Is Facebook comments taking long time to show up?

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1065]
ref: https://wordpress.org/support/topic/fb-comments-take-a-long-time-to-appear/

We need to test and find why it is happening

**Comment by nicholasgriffintn** [comment]
I am using Facebook Comments and I get these errors on pages:

`The resource https://3p.ampproject.net/1503083916053/f.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
amp:1 The resource https://connect.facebook.net/en_GB/sdk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
amp:1 The resource https://d-36190586151841577408.ampproject.net/1503083916053/frame.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.`

Definitely shouldn't be pre loading those links as comments don't load till the bottom of the page, same with the frame script, only needs preloading if you have a video embed at the top of every article.

Preload should only be for stuff right at the top of the page.

As for the speed, it is definitely a little slow but that's due to AMPs lazy loading, it's the same whenever you lazy load FB Comments, I'm not sure if there's much you can do on that side of things since it's probably due to Facebook's code.

**Comment by ahmedkaludi** [comment]
There's nothing we can do about it. It's from FB side.
