### ISSUE TITLE
Why does the plugin change 'ins datetime="xxxxx"' into 'instime'?

### ISSUE THREAD

**Issue by o6asan** [ahmedkaludi/accelerated-mobile-pages#1070]
WordPress's insert or delete tags are like `<ins datetime="2017-05-01T16:36:29+00:00"> </ins>
` or `<del datetime="2017-05-01T16:36:29+00:00"> </del>
`.

The plugin changes `<ins datetime="2017-05-01T16:36:29+00:00"> </ins>` into `<instime>` instead of changing `<ins datetime="2017-05-01T16:36:29+00:00"> </ins>` into `<ins> </ins>`, so Google Search Console complains about them.

How can I handle its complain?

**Comment by MARQAS** [comment]
ref: 
https://wordpress.org/support/topic/the-plugin-changes-ins-datetime-into-instime/

**Comment by Sejiro-Hiko** [comment]
Tested thoroughly, there don't seem to strip off any attributes in the tag or any validation issues.

**Comment by MohammedKaludi** [comment]
Yes, tested and seems to be working. so closing the ticket.

**Comment by o6asan** [comment]
Hi there!
Thanks so much.

**Comment by angelatwin333** [comment]
@o6asan . Sorry to bother you! I couldn't find any other way to reach you, not even through your BBS contact (NetOwl security blocked me from commenting there). Your website is down. I can't access your translation for Hyohaku anymore. Or for any domains titled o6asan. It says ERR_ADDRESS_UNREACHABLE. I didn't save your email address either, and since it was on said website, I couldn't email you either, hence I am contacting you here.

At first I thought the issue was with my server, but I realized it would happen regardless of device, browser of computers. I had a bunch of classmates try it with their respective servers, internet, and devices too-issue's with your website. Would you mind fixing it so I can read Hyohaku please?

Again, sorry for hijacking this forum, I couldn't find any other way of contacting you since BBS and your website is down. I'm not sure how github works, so I think I ended up commenting on all your forums (created an account just to try to reach you). I'm so sorry! Not trying to stalk you at all, just desperate because Hyohaku is down, plus Hyohaku is a personal favorite of mine to read. I can't find any other translations for Hyohaku either.

**Comment by o6asan** [comment]
@angelatwin333 ,
Thank you for informing me about my sites down. I had not notice my web server down until my reading your letter. I fixed it. I think you can reach my sites now.

I apologize to everyone on this forum for our bothering.

**Comment by angelatwin333** [comment]
Thank you so much!
