### ISSUE TITLE
Only one <figure> element is allowed in the article <header>: FB Instant Articles

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1127]
The analytics code is causing a problem in the validation of Instant articles. see the screenshot:
<img width="899" alt="greenshot 2017-09-11 11 24 06" src="https://user-images.githubusercontent.com/16532359/30545599-baed3b08-9ca7-11e7-9e02-86346683d00d.png">

**Comment by metrey** [comment]
The analytics code generated between 
`<article><header>...</header>..` with tag `<figure>` that cause the problem

But if place that block of code outside tag **header**, it's OK.

**Comment by ErikThiart** [comment]
Do you guys know when this will be fixed?

**Comment by ahmedkaludi** [comment]
@ErikThiart It'll be fixed in next update on 7 oct

**Comment by ErikThiart** [comment]
Sweet stuff!

On 30 Sep 2017 1:07 PM, "Ahmed Kaludi" <notifications@github.com> wrote:

@ErikThiart <https://github.com/erikthiart> It'll be fixed in next update
on 7 oct

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1127#issuecomment-333301521>,
or mute the thread

**Comment by youdivi** [comment]
Great support as always! Thanks! Looking forward next update on 7 oct!

**Comment by MohammedKaludi** [comment]
Fixed in #1157
