### ISSUE TITLE
SEO improvement?

### ISSUE THREAD

**Issue by physixfan** [ahmedkaludi/accelerated-mobile-pages#1208]
Before I install AMPforWP plugin, our blog has the headings in Google search results (see screenshot for what I mean). However, after installing AMPforWP, I got the AMP logo but I lost the headings in Google search results. Is it possible to have both??

![wechatimg65](https://user-images.githubusercontent.com/4311261/31291746-a4581c0a-aa85-11e7-9538-58b0d0d7078b.jpeg)

**Comment by ahmedkaludi** [comment]
Can you show me the preview of your results on AMP and Non-AMP?

**Comment by physixfan** [comment]
Here’s a page without AMP: 
![926a0054-5975-4405-87f0-d47a581b9f19](https://user-images.githubusercontent.com/4311261/31317967-2240131e-abff-11e7-9392-9ff46c1e6475.png)

Here’s a page with AMP:
![8e8d51ed-27a3-45fb-9275-ead19ce321bf](https://user-images.githubusercontent.com/4311261/31317972-329db5ae-abff-11e7-9281-19d3aa9da788.png)

**Comment by ahmedkaludi** [comment]
The links you see below the search results are called 'Site links', and as far as I remember, only Google decides when to and what kind of site links will be displayed.

**Comment by ahmedkaludi** [comment]
I don't think it's something in our hand. any opinions from others would be appreciated.

**Comment by mayanksharma9033** [comment]
Hi @ahmedkaludi,

I am moving this ticket to review and Q/A

**Comment by MohammedKaludi** [comment]
As @ahmedkaludi mentioned we have no control over it and it is up to google what to show and not. 

But I have gone through your sites Structured Data and found something not correct.

name attribute in Structured Data has some weird characters instead of sites name. Like this "name":"\u7f8e\u56fd\u4fe1\u7528\u5361\u6307\u5357"
Like this : http://take.ms/VHrLt

I know fixing this will not solve your actual query but improve overall sites SD. As I have mentioned it is up to google on what to show and it is up to us to properly setup Structured Data.

Hope it helps.
Mohammed Kaludi
