### ISSUE TITLE
cursor mispositioned

### ISSUE THREAD

**Issue by seoulrain** [ahmedkaludi/accelerated-mobile-pages#1223]
ios11
iphone6

screenshot : http://d.pr/i/FZS4nE

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn do have the iPhone 6 with iOS11? If so, please help.

I can fix this in two mins but I am unable to get the device, memory on my macbook is low so I can't run a big-arse emulator.

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi By chance I actually do, I'll take a look.

**Comment by nicholasgriffintn** [comment]
So I just tested this and it's actually a really simple fix, we just need to add "position: fixed; to the body when a model is open and that will fix the issue for Safari, I haven't tested if this will affect other browsers yet, however, I don't see how it will affect anything since it will only be enabled while the lightbox is showing. I will write up some code and launch a pull shortly for it.

**Comment by nicholasgriffintn** [comment]
So I just launched pull #1329, which should fix the issue, worked great in my testing on safari on a iPhone 6 with iOS 11.

I haven't tested it on other devices or browsers yet, however, I only added a position: fixed tag to the body when the html.i-amphtml-scroll-disabled is present, so I don't think it will raise an issue with other browsers.

**Comment by ahmedkaludi** [comment]
It's fixed in iOS 11.3. 

1. https://github.com/twbs/bootstrap/issues/24835#issuecomment-375709871
2. https://github.com/jgthms/bulma/issues/1774#issuecomment-380997339
