### ISSUE TITLE
Add a Share Count on the Social Sharing buttons. (Jetpack compatibility)

### ISSUE THREAD

**Issue by jeiseman** [ahmedkaludi/accelerated-mobile-pages#1244]

**Comment by ahmedkaludi** [comment]
@jeiseman and what plugin would it be related to?

More details please?

**Comment by jeiseman** [comment]
Jetpack sharing shows share buttons on the non-amp pages with counts for facebook and twitter. The Jetpack sharing doesn't show the buttons on the amp site (probably because it's implemented in javascript). The accelerated mobile pages has an option to show share buttons on amp pages but it doesn't show the share counts. This request is to show the share counts on the sharing buttons. You can see an example here comparing the non-amp page:
https://www.classical-scene.com/2017/10/09/robert-honeysucker/
With the amp page:
https://www.classical-scene.com/2017/10/09/robert-honeysucker/amp/
The sharing count only shows up on the non-amp page.

**Comment by MARQAS** [comment]
Hi @jeiseman, Many apologies for the delay. 

AMP does not allow the counter at the moment. And we can't add the custom JS. 
references: https://stackoverflow.com/questions/48880157/share-count-in-amp-social-share
https://www.ampproject.org/docs/reference/components/amp-social-share
https://ampbyexample.com/components/amp-social-share/

So I am closing this ticket for now. We can reopen it once we get the official support for the counter or custom JS.

**Comment by MARQAS** [comment]
Or If you have any other alternative solution then please reopen it or send a Pull request with the solution or you can even contact us at team@magazine3.com.
We want to solve all the problems which our users are facing, but at sometimes we just can't do anything except for things to go better(like this case).
We are unable to solve a few problems due to AMP restrictions, but I assure you once they allow things will be among the first ones to implement them. 
Hope you can understand.
