### ISSUE TITLE
#1051 fix cause lot of issues.

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1247]
Plain AMP URL loads ok:
https://www.aminhafestinha.com/festa-frozen/amp/ 

Any AMP URL with a query string parameter has a redirected.
example:
https://www.aminhafestinha.com/festa-frozen/amp/?utm_source=google
Redirects to
https://www.aminhafestinha.com/festa-frozen/?utm_source=google/amp

Ref: https://secure.helpscout.net/conversation/446715085/16943?folderId=1514170

**Comment by ahmedkaludi** [comment]
Another case:
In the last version the same url http:/www.teamworld.it/blabla/amp/?usqp=mq331AQCCAE= causes a redirect to http:/www.teamworld.it/blabla/?usqp=mq331AQCCAE=/amp loading the normal version of the site (and bypassing the static cached version because of the var).

https://wordpress.org/support/topic/dramatic-loading-issues/#post-9581222
