### ISSUE TITLE
Automatically add "/amp" to menu items

### ISSUE THREAD

**Issue by KenYN** [ahmedkaludi/accelerated-mobile-pages#1269]
We have the [instructions on how to set the navigation menu](https://ampforwp.com/tutorials/article/add-menus-amp/), but existing links will be published without the trailing "/amp", even for pages that are by default to be published as AMP.

I worked around the problem by simply duplicating the links with Custom Links to the AMP versions, but it should happen automatically.

(BTW, this might also be the reason why Google is deciding my AMP home page does not sufficiently match my normal page and refusing to index it.)

**Comment by Frenchomatic** [comment]
I doubt it is the reason why they are not indexing your home page. It is far more likely to be a quality or guidelines issue.  If I understand correctly,  the problem of doing this is what happens if you want a mixed menu on your AMP version. Using custom links is not a hack - it is a valid thing to do. You then have full control over your menu. You simply create an AMP header menu and an AMP footer menu - you set up the links as you want.

**Comment by ahmedkaludi** [comment]
@KenYN if you want to automatically add /amp at the end of the menu then use the menu, if not then select the pages manually. As simple as that.

That has nothing to do with your indexing. For indexing, try to monitor webmaster tools.

**Comment by Frenchomatic** [comment]
Well done - this would not make any sense and especially for those with mixed menus of amp and non-amp urls.
