### ISSUE TITLE
Accented characters - structured data + meta

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1317]
Accented characters like é, è, à  or  dashes like '-', _'  are been rendered as decimal or unicode in structured data elements like headline and meta output like <title>, <meta description=.  This is not how they are rendered in normal wordpress pages. However, it doesn't seem to be affecting google SERPS where the characters are being correctly rendered. Perhaps not worth the effort of investigating.

**Comment by MARQAS** [comment]
Hi @Frenchomatic , 
We have checked it and it seems that the bots are able to read it properly, and you can see the test here as well: 
![image](https://user-images.githubusercontent.com/15303814/33129600-6cf3e270-cfb6-11e7-8637-66b708a176cf.png)
So we decided that we will keep it as it is, instead of adding few more code or change the existing code of vendor. 

Let me know what you think about it

**Comment by Frenchomatic** [comment]
Seems ok then - as Isaid it it not affecting the SERPS
