### ISSUE TITLE
Structured Data Validation Issues

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#136]
There are alot of problems with Structured data validation. I really need help in this one @MohammedKaludi @nicholasgriffintn
1. One of the popular one is that the 'Logo is not available'. That's because the logo needs to be uploaded from the customizer > site icon. but then our users don't realize this... Plus it also gets set as favicon.
2. There is also sometimes an image width issue, see https://search.google.com/structured-data/testing-tool/u/0/?url=http%3A%2F%2Ftechpp.com%2F2009%2F09%2F16%2Fdownload-cyberlink-power2go-5-5-free-license%2Famp%2F#url=http%3A%2F%2Ftechpp.com%2F2009%2F09%2F16%2Fdownload-cyberlink-power2go-5-5-free-license%2Famp%2F

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi Hey,

First off, I have a pull ( #119 ) that would allow users to set a custom favicon and other icons, so that would fix the logo being shown as a favicon, and instead, it will show the users uploaded favicon.

For the "Logo is not available" issue, you could set a default upload for the logo, which would fix the problem, and it would push users to want to upload a logo, as the one shown is not their logo.

You could also show a notification on the page that shows until the important information such as the logo is uploaded.

For the second issue, it seems that because you are calling person in the structured data, Google is expecting to see an image of that person, this is so they can show the author's image in the search results next to the result.

You could solve this by calling the author's avatar in the schema, similar to this:

https://codex.wordpress.org/Function_Reference/get_avatar

**Comment by nicholasgriffintn** [comment]
You could set this code yourself by adding code such as this to the headers of pages:

```
<!-- AMP Schema  -->
<meta itemscope itemprop="mainEntityOfPage" itemtype="https://schema.org/WebPage" itemid="<?php the_permalink(); ?>">
    <span class="site-schema-hide" itemscope itemprop="publisher" itemtype="https://schema.org/Organization">
      <meta itemprop="name" content="<?php esc_attr( bloginfo( 'name' ) ); ?>">
      <meta itemprop="url" content="<?php echo $redux_builder_amp['amp-app-favicon']['url']; ?>">
       <span class="site-schema-hide" itemscope itemprop="logo" itemtype="https://schema.org/ImageObject">
            <meta itemprop="url" content="<?php echo $redux_builder_amp['amp-app-favicon']['url']; ?>">
<meta itemprop="headline " content="<?php the_title(); ?>">
<?php if ( has_post_thumbnail( $cb_post_id ) ) { ?>
    <span class="site-schema-hide" itemscope itemtype="http://schema.org/ImageObject" itemprop="image" >
        <meta itemprop="url" content="<?php echo $thumb_url ?>">
        <meta itemprop="width" content="512">
        <meta itemprop="height" content="300">
    </span>
```

That code would also require my pull #119, but you could make it work without.

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn But will it overwrite the AMP's structured data? Will it not conflict in the Structured data testing tool?

**Comment by nicholasgriffintn** [comment]
So I have created a quick pull ( #141 ), which adds that code in a way that I think will work, I have tested it and it does indeed load all of the stuff.

And no, it doesn't overwrite, it would be placed alongside other schema and I presume that Google would take any valid code, however, I am unsure. It would require testing elsewhere as I cannot.

**Comment by nicholasgriffintn** [comment]
Hey @MohammedKaludi, the code you added does seem to fix the logo not being included, however, it won't fix the image validation issues.

The image issue is because it'a not adding the featured image for posts to the schema in some installs, if you have Yoast SEO it should, however, if you don't it won't.

**Comment by nicholasgriffintn** [comment]
On top of that, this loads the logo that was uploaded into the schema, which is normally going to be quite wide. Google expects a 48 x 48 image, so you would need to load a custom icon as I have suggested in pull #141.

**Comment by MohammedKaludi** [comment]
I'm in a hurry, i have reopened the issue, so i don't miss it. 

Will go through your comments, once i'm back.

**Comment by nicholasgriffintn** [comment]
Okay @MohammedKaludi,

Well, I have made this pull ( #145 ) that will implement what I suggested.

Basically, the logo for organisation schema should be 48 x 48, so it needs a custom icon, this pull will load that.

I also added some code that I think would work in adding the featured image to the schema, however, I have not tested that yet. And because we are loading a custom icon for the schema anyway, the pull then goes on to load a favicon, app icon and a manifest on AMP pages, all of which you need to show an icon for the page in browsers, mobile and desktop.

**Comment by ahmedkaludi** [comment]
Hey @nicholasgriffintn 

I'm so sorry for not getting back to you. My inbox is flooded with AMP emails lately. There was a fix we recently added in an update which seems to have resolved the issue for the users.

Can you please review the current code and share your feedback? I will appreciate that. It will be a good idea on what we should work on before sending a pull request, so we know who is working on what. Let me know your thoughts.

**Comment by ahmedkaludi** [comment]
Continuing the discussion from #134
