### ISSUE TITLE
AMP Allow selector in the "The Content"

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1588]
AMP Allow selector in the "The Content"

Ref:  https://secure.helpscout.net/conversation/501844681/20187?folderId=1060551

- [x] Selector

- [ ] Experiment

- [x] Carousel

**Comment by ahmedkaludi** [comment]
And also allow amp-experiment tab

https://wordpress.org/support/topic/how-to-include-custom-html-per-page/#post-9850796

**Comment by ahmedkaludi** [comment]
and allow <amp-carousel as well. https://wordpress.org/support/topic/carousel-function-and-homepage/

**Comment by zabi09** [comment]
Allow Tab Panels with amp-selector

Ref: https://secure.helpscout.net/conversation/519866456/21424?folderId=1680011

**Comment by MARQAS** [comment]
amp-selector contains script tag which will be removed by the sanitizer, so it can be added in this way. 
https://wordpress.org/support/topic/how-to-include-custom-html-per-page/#post-9850796

**Comment by ahmedkaludi** [comment]
- [ ] Removed https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/693bcc308de556a97dede7d91110459289fdeb9b because it was causing the issue, It was there while we were fixing https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1588

## Testing 

- [ ] Test it with AMP tabs and see if they are working,

- [ ] Test with AMP carousel and make sure it's working

- [ ] http://take.ms/yNnFs is this happening only on the AMP and that too on that specific page? because looking at the code, it seems like otherwise.
