### ISSUE TITLE
Compatibility with Table of Contents Plus

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1673]
the amp-custom style is not loading properly because of this plugin 

Screenshots:
http://take.ms/4mUGB
http://take.ms/N0ZIw
http://take.ms/In5Zf

Ref: https://secure.helpscout.net/conversation/509651933/20553?folderId=1060551

**Comment by MARQAS** [comment]
The issue of the user is resolved. 
Is this the proper reference? or wrong ticket?

**Comment by ahmedkaludi** [comment]
@marqas 

I don't know if the user has resolved or something. Maybe he did.

When we're using that plugin, once we add the shortcode: https://monosnap.com/image/2D9q7AYQD8NfhUuP0vrD1QrXX9HQGc

It adds certain Style tag CSS https://monosnap.com/image/1BxGl0XZcc6VQlp3X3txvKD2tYO8tL

Which makes the whole AMP Validation error, and make it look like https://monosnap.com/image/G9ztAmgrVG2HJONlY9cQ6HxaOnrtPi

that tve_more_tag style tag should not load at all.

**Comment by MARQAS** [comment]
It's not due to that plugin, I have tested it and even tested on users end.
And tve_more_tag is from Thrive not TOC. 
Now the user is only having an issue due to type in ul tag but we are already removing it but don't know why it is not getting applied to his end.
Contacted the user waiting for his reply.

**Comment by MARQAS** [comment]
Contacted him again
