### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1836]
When a Featured image is not set, it getting validation errors.
see this screenshot:  http://take.ms/6G8zg

Ref:  https://secure.helpscout.net/conversation/537628182/22857?folderId=1060554

**Comment by beingsmart3** [comment]
One  more
Ref:  https://www.familiesonlinemagazine.com/tag/teens/amp/

**Comment by beingsmart3** [comment]
one more

Ref:  https://secure.helpscout.net/conversation/523101375/21628?folderId=1914712

**Comment by MARQAS** [comment]
1": It was due to the deletion of images. Informed the user.

2: He is having error only on one post and the reason is unknown, I don't know how he setup that post, even his non amp is showing the same error. Informed him, waiting for his reply [https://secure.helpscout.net/conversation/530041123/22234?folderId=1060556 ] 

3: The errors are due to NewsPaper AMP Theme

**Comment by MohammedKaludi** [comment]
:+1:
