### ISSUE TITLE
Issue with the articles with tags " in title in Swift theme

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2004]
Issue with the articles with tags " in title in Swift theme

REF: https://secure.helpscout.net/conversation/558464584/24314?folderId=1680011

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko Yes the issue was recreated and solved on users site by wrapping the title in `htmlspecialchars()` function

`Example: <a class="s_tw" target="_blank" href="https://twitter.com/intent/tweet?url=<?php the_permalink(); ?>&text=<?php echo htmlspecialchars( get_the_title() ); ?>">`

wrap all the titles with `htmlspecialchars()` in all the social sharing elements in all the designs.

**Comment by MohammedKaludi** [comment]
:+1:
