### ISSUE TITLE
In some edge cases the content is not rendering

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2035]
In some edge cases, the content is not rendering in AMP version 0.9.85 and its working fine in 0.9.74.1 (stable version) and I don't know the reason.

Ref:  https://secure.helpscout.net/conversation/562032464/24601?folderId=1914712

**Comment by Sejiro-Hiko** [comment]
It was due to ampforwp_is_front_page() and is_front_page() where returning false and due to which amp_content was not generating and for a strange reason after I set up the blog page (because is_home returning true for the custom front page)  and then unset the blog the content starts appearing on user's end.

**Comment by MohammedKaludi** [comment]
:+1: Closing the ticket as it was a one-off issue on users website. And we were able to fix it.
