### ISSUE TITLE
How to remove a big gap between the header and the post content?

### ISSUE THREAD

**Issue by Earngurus** [ahmedkaludi/Accelerated-Mobile-Pages#207]
How to remove a big gap between the header and the post content?

check the screen shot?

http://prnt.sc/d753vw

**Comment by nicholasgriffintn** [comment]
Without a link to your site, it is hard to tell you how to do that.

I suspect that is an ad slot and you probably haven't set it up properly, or you didn't mean to set it up.

**Comment by Earngurus** [comment]
Here is my link

http://www.earngurus.com

**Comment by nicholasgriffintn** [comment]
I just took a look.

The problem is that you have setup the ad unit at the top of your page incorrectly and the iframe for the ad is actually 404ing.

You can see it in this screenshot:

https://www.dropbox.com/s/5pvyyvsr8n9a1me/Screen%20Shot%202016-11-15%20at%2018.52.02.png?dl=0

To fix it you simply needs to go to the "ads" section of the AMP plugin and make sure all of your inputted stuff is correct.
