### ISSUE TITLE
AMP pixel not loading

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2087]
Jetpack stats not loading in AMP but loading fine in non-AMP.

Ref: https://secure.helpscout.net/conversation/544821968/23466?folderId=1964340

**Comment by musebridge** [comment]
I think the Automattic AMP Plugin works with Jetpack - by adding some sort of WP Pixel, due to a recent update. But the AMP for WP plugin doesn't implement this. IT would be helpful if the plugin can work on the existing base created by the Automattic AMP Plugin, instead of attempting to crate a new Base.

**Comment by jeherve** [comment]
For reference:
https://github.com/Automattic/amp-wp/pull/246

**Comment by MARQAS** [comment]
amp-pixel is loading properly in AMP. 

I've checked on user's website as well and it is working fine.
ref: https://secure.helpscout.net/conversation/544821968/23466?folderId=1060556

**Comment by MARQAS** [comment]
@musebridge and @jeherve can you guys update us the status of this issue?

**Comment by ahmedkaludi** [comment]
We have checked and jetpack pixel seems to be working
