### ISSUE TITLE
GDPR and Cookie consent

### ISSUE THREAD

**Issue by MayankParmar207** [ahmedkaludi/accelerated-mobile-pages#2152]
Hi,

The Cookie consent feature in AMP For WP seems incomplete.

It should be like this.

![gdpr](https://user-images.githubusercontent.com/36712929/40112136-ae6c7410-5922-11e8-856e-b7597b7585d4.jpg)

The Learn More button link option is missing. Please add asap.

**Comment by MohammedKaludi** [comment]
GDPR Compliancy to only serve in the EU and don't want to serve it everywhere else.

Ref: https://secure.helpscout.net/conversation/571581581/25390/

**Comment by MayankParmar207** [comment]
@MohammedKaludi It's 25th already. No updates to enable this? It's really important, I hope you understand.

**Comment by valeturchi** [comment]
I don't understand why you don't give GDPR a higher priority. It's almost May 25th and your plugin is not compliant! Is there anything more important than this?

**Comment by MohammedKaludi** [comment]
Hello,

All the issues related to gdpr compatibility has been fix and it was under testing. 

We take it very seriously, and we are going to push an update in few hours.

Please be assured that it is our one of the priorities.

I apologise for the delay, I Know if we have pushed it a little earlier, that would have been much better.

Mohammed Kaludi,

**Comment by valeturchi** [comment]
Hi, I have updated the plugin to its latest version, but GDPR option still doesn’t work at all! When I select it no popup shows up 🙁 Honestly speaking, I don't understand why it is taking so long to make the plugin GDPR compliant! I have already disabled GA and ads from AMP version of my blog since May 24th, waiting for the plugin to be compliant with GDPR. Could you check it please? Thanks! Vale

**Comment by Sejiro-Hiko** [comment]
@valeturchi what you mentioned is strange the plugin is made fully compatible with GDPR, can you please reach us out at https://ampforwp.com/support/ and we'll look into your issue and make sure that GDPR works fine on your end.

**Comment by MohammedKaludi** [comment]
@valeturchi this has been fixed can you please confirm that it is working on your site?

**Comment by valeturchi** [comment]
Hi Mohammed, I am afraid this hasn't been fixed at all, since one of your colleagues already told me GDPR option works only for https websites and mine is not. Honestly speaking, it's quite absurd, since I never planned to buy an SSL certification and I don't even own an e-commerce, but if I don't do it my AMP website won't be compliant with GDPR law. If you could give a solution I would really appreciate. Thanks!

**Comment by Zabi09** [comment]
@valeturchi 
Sorry to say you but SSL is must for your website if you want GDPR option and yes if you cannot afford to buy the SSL certification you can also use free SSL from the websites like let's encrypt etc..

So that you can use GDPR option for your website.

**Comment by MohammedKaludi** [comment]
GDPR is properly working and tested on multiple websites.
Closing the ticket.
