### ISSUE TITLE
The License keys are getting disappeared from the AMP Extension Panel

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2261]
Description: The License keys of the extensions are getting disappeared from the AMP Extension Panel

Ref: https://secure.helpscout.net/conversation/599769235/27932?folderId=1680011

**Comment by ahmedkaludi** [comment]
- [ ] and there's one more request from Yudha
 is it possible to hide the liscense key form? Or how to restric/protect the plugin or make the plugin expired after 1 year of use & prevent them to use the key for their another domain? Because i think my client could copy the liscense key and use it in another domain

**Comment by MohammedKaludi** [comment]
:+1:
