### ISSUE TITLE
Meta robots tag not being rendered

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2351]
It is a bit frustrating when having to check things which get fixed but several versions later they no longer work.

Meta robots - noindex, noarchive etc which are set in Genesis framework are no longer being rendered. This means there is an issue with AMP takeover and preventing pages like legal and privacy from getting indexed.

**Comment by ahmedkaludi** [comment]
@Frenchomatic Are you checking it in the 0.9.97.4 or the 0.9.98 Beta ?

**Comment by ahmedkaludi** [comment]
If you can share the exact environment details on team@magazine3.com  then I can analyze the exact problem and fix them

**Comment by Frenchomatic** [comment]
Sorry - design 2 - AMP takeover (or not as the case maybe) - Version 0.9.97.4 . Genesis SEO title and meta description appear to render ok but the meta robots tags don't show anymore.

**Comment by MARQAS** [comment]
Hi @Frenchomatic,
Check the 'Advanced Indexing' sub-section inside SEO section of AMP Options Panel. Is 'URL Inspection Tool Compatibility' option enabled?
It seems that Google recently made some changes in URL inspection Tool due to which noindex in AMP is no longer valid and it is causing validation errors. This is the reason we made some changes in noindex part recently.

**Comment by Frenchomatic** [comment]
Yes it is set to on - the problem is most of my sites are in AMP takeover so all pages are canonical. Pages like privacy and legal info are now going to get indexed. If noindex is set on those pages, it doesn't matter that they aren't valid AMP.  The point is that they don't get indexed at all.

**Comment by MARQAS** [comment]
If they are not valid AMP then Google will not indexed them.
If you want to have noindex then try disabling the URL Inspection Tool Compatibility option. I am sure it will resolve your problem.

**Comment by Frenchomatic** [comment]
Thanks - I now see if I turn that inspection option off - the noindex appears for my legal and privacy pages.  Trying to understand the consequence of not using that tool.

**Comment by MARQAS** [comment]
We have added that option to remove noindex from AMP pages as it will throw errors in Google Search Console.

**Comment by Frenchomatic** [comment]
But Marqas - how do you noindex a privacy page for example which happens to be AMP valid in AMP takeover? Do you see the problem?

**Comment by Frenchomatic** [comment]
Maybe I am not understanding fully - If the inspection tool throws errors because the page is non-valid then that is fine because it should do. The tool is simply confirming that your legal or privacy page is not AMP valid and is not being indexed either. 

Think about it like this - you have a site with a legal page - the canonical is noindex. There is an AMP version of that page because it fits in nicely with the AMP version of the site. You won't want the AMP  version indexed either. You could hide the AMP version of that legal page but you don't want to send people back to the canonical version ( you will then be taking them completely out of the AMP version). 

In the case of AMP takeover, Google sees just one version of the web site. You wouldn't want your legal page to be indexed on desktop or on mobile. 

In both cases you may want to be able to use the inspection tool. So I don't understand why you remove noindex just because you may want to use the inspection tool to check other urls.

**Comment by MARQAS** [comment]
Neither we are using inspection tool nor we have created it, it is Googles URL inspection tool. You can read more about it here: https://webmasters.googleblog.com/2018/06/new-url-inspection-tool-more-in-search.html
And with this update noindex in meta robots in not valid anymore. Many of our users came to us with lots of errors in their Search Console due to this. So to avoid those errors we made this option which will remove noindex from the AMP sites to avoid errors. 

There are only 2 possible solutions for this: 
1. Add the noindex in meta robots and ignore the errors in Search Console.
2. Remove the noindex and Turn off the AMP from those pages on which you don't want AMP. 

Google is simply saying if you don't want it to index those AMP pages then simply don't make them AMP compatible. 

As we don't control it, we can't do anything about it. All we can do is help our users as much as we can and that's what we are doing by providing them with different solutions.

And regarding your query about AMP Takeover, if you don't want noindex then you can turn off AMP from those pages then it will be your normal page without AMP. But as you said you put the noindex in canonical pages ( i.e., non-amp) then you don't have to worry about it, right?

**Comment by Frenchomatic** [comment]
I have settled with turning the option off so I can still noindex and noarchive specific pages in the genesis SEO settings for a page. These will not get indexed or cached as AMP pages. They may show up as non-AMP valid in the inspection tool but that is fine because I don't want them indexed anyway.  I think the confusion here on my part is what you called the option.

**Comment by MARQAS** [comment]
Any suggestion on how we can improve it?

**Comment by Frenchomatic** [comment]
Difficult as it requires explanation doesn't it. Remove noindex, noarchive, nofollow tags. Then where you have the link you could say that pages will not be valid AMP.

**Comment by ahmedkaludi** [comment]
@Frenchomatic Are your Privacy and Legal Page getting indexed?

**Comment by Frenchomatic** [comment]
No its fine at the moment.  You are correctly picking up the genesis robot meta settings which produces this 

`<meta name="robots" content="noindex,noarchive,noodp,noydir"> `

**Comment by Frenchomatic** [comment]
But it is working as it should. The only thing to remember is that the inspection tool needs to be turned off or you can't use noindex, noarchive
