### ISSUE TITLE
amp img error when images are coming from the wordpress cdn

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2444]
The user is facing the error of width and height amp Img is set to invalid because the images are coming from the WordPress CDN and when we enabled the minify option than the error gets fixed also the images are loading. 

Screenshot:  http://take.ms/rIerE

Ref:  https://secure.helpscout.net/conversation/635858982/31587?folderId=1914712

**Comment by Zabi09** [comment]
This issue was coming from the "Clearly – WordPress optimization plugin" and the problem was coming from the HTML minify option of that plugin and if we enable our plugin's minify option then the problem will be fixed and I have also contacted them for the solution - https://wordpress.org/support/topic/error-on-the-html-minify-option

**Comment by MohammedKaludi** [comment]
Plugin author wrote: 

> I tested a new version of the plugin with your plugin. Conflicts no longer arise.
