### ISSUE TITLE
Missing conditional tag for get_the_tags() causing "Invalid argument supplied for foreach()" error

### ISSUE THREAD

**Issue by huuhoang6593** [ahmedkaludi/accelerated-mobile-pages#2456]
For the posts that don't have any tag, the following code caused so many errors:

`foreach ($all_tags as $tagskey => $tagsvalue) {
	$tagsOnPost[] = $tagsvalue->term_id;
}`

PHP message: PHP Warning:  Invalid argument supplied for foreach() in {my_site_path}/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4799
PHP message: PHP Warning:  Invalid argument supplied for foreach() in {my_site_path}/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 248

Should wrap the code in a conditional tag, checking if **$all_tags** is not empty.

**Comment by MohammedKaludi** [comment]
Thank you for reporting the issue, we are aware of this issue and this has been fixed in a recent commit which you can check here https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2e23a0f2ae2df8e4400492bb4d5f672fa37c74ca

This code will be pushed in a minor update that we are going to release in couple of days. 

Do let me know if you have any other feedback.

**Comment by MohammedKaludi** [comment]
:+1: ready to add in master.

**Comment by MohammedKaludi** [comment]
Please Consult me before closing the ticket.

**Comment by Omair52** [comment]
pushed in 0.9.97.17
