### ISSUE TITLE
Fatal error with Setka Editor

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2468]
They are extending the AMP_Base_Sanitizer and using $this->root_element which is not present in the 0.4.2 version of AMP.

**Comment by MohammedKaludi** [comment]
Need to update vendor-changelog file

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.12

**Comment by mdsam10** [comment]
Ref: https://secure.helpscout.net/conversation/623115147/30488?folderId=2206768

Desc :   the problem is that required scripts for these components `amp-animation` and `amp-position-observer` are added with incorrect src src="http://1". And for one animated element in the post one `amp-position-observer` is created and 6 `amp-animation` elements with the same ID.

<script custom-element="amp-position-observer" src="http://1" async></script>
 <script custom-element="amp-animation" src="http://1" async></script>

**Comment by MARQAS** [comment]
The issue was from the setka editor itself, the updated code has been sent to them.
