### ISSUE TITLE
In Feature Module the Bullet points are not aligned correctly

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2554]
In Feature Module the Bullet points are not aligned correctly it stays at center when we select the left and right Align. Hence Right and left alignment is not working.

Ref: https://secure.helpscout.net/conversation/662236063/34119?folderId=1914712

Screenshot: http://take.ms/JkGld

**Comment by MohammedKaludi** [comment]
make the text translatable 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/772c9aa4bbeef55136da43203ba77c7b95a6833d#diff-78bca971084f2523b6a9248029945ccfR122

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by beingsmart3** [comment]
the Issue still persists in the Swift theme Beta version:  http://take.ms/irRKx
and on other 1,2 &3 designs Feature module loads twice

**Comment by RajuJeelaga** [comment]
- [ ] According to design, list of items bullet points are showing and that is correct way that is coming, and we are providing the alignment options in the page builder for list of items, so with that option we can align it. 

 [ ] Page builder Modules are Repeating twice in Design 1,2 and 3, and this problem is showing in Beta only, Master Branch it is working fine in all the Designs,
Please check the screenshot in Beta https://monosnap.com/file/xgcy5IDFog5yhHr7EcgN3VpZi2FzVB

@MARQAS @Zabi09

**Comment by MARQAS** [comment]
The double content issue was due to improvements made in #2873

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
