### ISSUE TITLE
Undefined variable...

### ISSUE THREAD

**Issue by stevetheadi** [ahmedkaludi/accelerated-mobile-pages#2558]
Hi

the AMP version of my homepage is fine.

However, all the other pages and posts have ‘undefined variable…’ error messages all over them. 

See: https://ibb.co/d1nOpz

How can fix this?

Great plugin, by the way. Love it!

https://www.broughtonschoolofmotoring.com/how-to-get-your-first-provisional-driving-license/amp

**Comment by MohammedKaludi** [comment]
Hey @stevetheadi 

Thank you for using the plugin and the error is coming from "Schema" plugin.

I see this in the error 
`Notice: Undefined variable: json in /var/sites/b/broughtonschoolofmotoring.com/public_html/wp-content/plugins/schema/includes/integrations/amp.php on line 34`

It is just a notice and coming due to debug mode is enable. You can deactivate it by refering this tutorial.
https://premium.wpmudev.org/blog/debugging-wordpress-how-to-use-wp_debug/

Also, we have developed a new extension that is fully compatible with AMP and imports all the data from your existing plugin and it is very stable.

You can download it from WordPress.org for free: https://wordpress.org/plugins/schema-and-structured-data-for-wp/

Please do let me know your feedback.

**Comment by stevetheadi** [comment]
Many thanks for the quick response!

As you suggested, I've set debug to false in wp-config and the error messages have disappeared. I like the look of your Schema extension and will be giving it a try. 

Thanks again.

**Comment by stevetheadi** [comment]
Hi guys,

Can you tell me why Google says this is not an AMP page (nor does it link
to an AMP page)?

https://www.broughtonschoolofmotoring.com/pull-push-its-not-difficult/amp

best wishes

Steve Watson

**Comment by MohammedKaludi** [comment]
Hey Steve,

It's 11 p.m. here and I will check it in the morning once I reach the office and will let you know why it is showing an invalid page. 

Thanks 
MK

**Comment by stevetheadi** [comment]
Thanks my friend!

Much appreciated.

best wishes

Steve Watson

**Comment by Zabi09** [comment]
Hi @stevetheadi 

I have tested your page and it's showing as a valid AMP page in Google AMP test - https://search.google.com/test/amp?id=yJpzq56mg1rTwNxhEUL94w

Will you please check once again and please wait for some days and that page will get indexed in webmaster tool

Hope it helps

**Comment by stevetheadi** [comment]
Many thanks!

All seems to be ok now, as you say it was probably a caching issue.

best wishes

Steve Watson
