### ISSUE TITLE
HTML content between <pre> tags are not rendered on the browser

### ISSUE THREAD

**Issue by bishwambharsen** [ahmedkaludi/accelerated-mobile-pages#2568]
I run a tutorial blog about salesforce lightning. I include code blocks in almost all my posts. They are visible in the normal version but in the AMP version they are never rendered. Kindly fix this or guide me to the right file and I will do it myself and contribute here.

**Comment by bishwambharsen** [comment]
![img_3933](https://user-images.githubusercontent.com/42896415/45909292-9b623100-be1e-11e8-97c1-c8e3a3747ffb.PNG)
![img_3932](https://user-images.githubusercontent.com/42896415/45909293-9b623100-be1e-11e8-813f-904c6fc07f7a.PNG)

**Comment by Zabi09** [comment]
@bishwambharsen I have checked your website and found that you are using "attribute" tag and also the "recordform" tag which is not allowed in AMP version and due to that it's not appearing in the AMP version - https://monosnap.com/file/GesXLz57HI5pLDlGtgqEWvu4XSAgl5 and as far as the pre tag is concerned it will render perfectly in AMP version.
Non-AMP - https://monosnap.com/file/kGI9GdGrxZ2DsS9PQEZXRaVL4vN9te
AMP - https://monosnap.com/file/88pXUuaygHHfnuYdhiRxVpQSjA5Obs

Will you please use the tags which are allowed in AMP and I am sure that it will work.

Hope it helps,

**Comment by bishwambharsen** [comment]
Hi,
Then how come it is rendered properly on this page? It uses the same tags.

https://www.sen-force.com/sample-student-app-with-multiple-components-and-events-and-a-lightning-spinner/amp/

**Comment by Zabi09** [comment]
@bishwambharsen You won't have any invalid attribute on this page - https://www.sen-force.com/sample-student-app-with-multiple-components-and-events-and-a-lightning-spinner/amp/

This is the Best example - on this page you have two 'pre' tags and in which one is working and another one is not working - https://www.sen-force.com/sample-student-app-part-3/amp/

The 1st pre tag which is not working consists of invalid attributes which I have mentioned above - http://take.ms/5K3XI and http://take.ms/mQETM

And the 2nd pre tag is working perfectly because there is no invalid tag - http://take.ms/hdezJ

**Comment by Zabi09** [comment]
@bishwambharsen Will you please contact us on team@magazine3.com and also ref to this GitHub ticket So that I will personally check the issue and let you know.

**Comment by bishwambharsen** [comment]
Sure
