### ISSUE TITLE
Twitter Option and Pretty Permalinks for Twitter Share? Option generate the same URL.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2662]
Reference: 
https://secure.helpscout.net/conversation/698702253/39152?folderId=2090438

When twitter option is enabled it gives the complete URL, but when Pretty Permalinks for Twitter Share? Option is enabled it should generate a shorter URL such as ( https://www.example.com/?p=999 ) in all the Designs.

**Comment by MohammedKaludi** [comment]
escaping required

**Comment by MARQAS** [comment]
Need Proper escaping and code improvement

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
1. incorrect function added instead of variable `$amp_permalink`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b4a621addfd1ac8a3bfc5d4862c7a6daa2d9f9a7#diff-9bf04cd42bc2066da77791b1697c5481R165

2. escaping missing for `$data_param_data`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b4a621addfd1ac8a3bfc5d4862c7a6daa2d9f9a7#diff-6aa5512f7dd8d5ce60fc97b0f340912cR1280

**Comment by MohammedKaludi** [comment]
escaping still missing in two files 
https://monosnap.com/file/0wh15t4gLvQVKZhCTqXzCfTIlnlmey

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
