### ISSUE TITLE
Lightbox for image does not work when link [anchor tag] attached to images 

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2695]
If we add the anchor tag to the image then lightbox feature does not work.
<a href="#"><img src=""/></a>

to solve it remove the anchor tag from the images [the_content images] when lightbox for the image option is enabled.

Ref:https://secure.helpscout.net/conversation/708807459/40467?folderId=1914713

**Comment by MohammedKaludi** [comment]
this will remove the ahref for all the urls regardless of amp or non-amp

this hook should be connected with `pre_amp_render_post` or something similar to avoid that.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0941332b4030ddd6ab8ed82ab22444d81e9f4c44#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6831

**Comment by pegazee** [comment]
I've added the image in the 'a' tag and I want to redirect the when user clicking on the image. but in the amp, instead of redirecting it's opening the image in lightbox ( when "lightbox for image" is enabled ).

So, I think it's doesn't make sense to apply the lightbox on the 'a' tag images.

**Comment by Zabi09** [comment]
Agreed with @pegazee and discussed with @ahmedkaludi and closing this ticket

**Comment by ahmedkaludi** [comment]
We run our website on a professionally designed theme (Pinstagram from Mythemeshop) and that theme requires us to upload all the images on the website with the option 'Link to' - 'Media file', which we are doing on our website since last 7 years and the lightbox feature is working fine with these settings, and we believe it is the correct and logical thing to make the lightbox feature work.

But, on AMP pages, the lightbox feature only works when we upload the image with the option 'Link to' - 'None', which also only makes the thumbnail size of the image bigger (doesn't actually load the real image of the actual pixels).

Now the thing is, we want all the images which we have on our website to load properly with the lightbox feature because we have many thumbnail size images which require users to click on it to view it properly.


Example page:
Non-AMP Page: https://starsunfolded.com/salman-khan/
AMP Page: https://starsunfolded.com/salman-khan/amp/

**Comment by akashagrjsr** [comment]
Steps to recreate 
1. Add media file and select option
  Link to: Attachment File
  Link To: None
  Link To: Custom Url

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
