### ISSUE TITLE
Integration with Rank Math SEO

### ISSUE THREAD

**Issue by Omair52** [ahmedkaludi/accelerated-mobile-pages#2701]
Reference: https://secure.helpscout.net/conversation/719902355/43202?folderId=1060551

**Comment by MARQAS** [comment]
They have added the compatibility of other SEO related things, only concern was Structured Data

**Comment by MARQAS** [comment]
@MyThemeShop,
I made the necessary changes, there are only 2 things left.

Description of FrontPage and to solve this use the correct ID for AMP FrontPage in your code. I stopped the description from our plugin when Rank math is activated. So use ampforwp_get_frontpage_id to get the AMP FrontPage ID.
Canonicals. I see that you are directly removing the hook of canonicals and adding your own. Instead of that, use our filter ampforwp_modify_rel_url to modify the canonicals.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready

**Comment by MohammedKaludi** [comment]
Rank Math SEO Plugin compatibility fully added check #2736 for more info
Pushed in 0.9.97.32
