### ISSUE TITLE
All the media queries should load in single media query only - http://take.ms/jfFdu

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2711]
with reference to: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2471

**Comment by ahmedkaludi** [comment]
and  

- [ ]  The margin and padding should have two 2 values if the same values are repeating - http://take.ms/0od2q (This Css Pregmatchs are not working)

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
prefix missing in function name

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b4bbb3fbac5acceb42eb76edc847c833fe9a0212#diff-45752acf5e8ea05d2224fa9a73c54c7aR505

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.97.33, closing the ticket.

**Comment by TMsravan** [comment]
Ref: https://secure.helpscout.net/conversation/813537998/61469?folderId=2632030

Instead of targeting all related classes in one media query it gets targeting individual and creating more CSS and raising an issue: The author stylesheet specified in tag 'style amp-custom' is too long - document contains 50458 bytes whereas the limit is 50000 bytes.

I have imported the layout where the issue is raising. Layout name "layout-29032019"

**Comment by pegazee** [comment]
When merging in master, need to check the `ampforwp_pb_autoCompileLess()` function code.

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
