### ISSUE TITLE
 I activate the plugin, my site displays a server 503 error. The issue resolves after deletion of the plugin.

### ISSUE THREAD

**Issue by khurram55pk** [ahmedkaludi/accelerated-mobile-pages#2769]
When I activate the plugin, my site displays a server 503 error. The issue resolves after deletion of the plugin. how i can fix it

**Comment by Zabi09** [comment]
Hi khurram55pk,

Sorry for the inconvenience, In some cases, the error will appear if you already have AMP plugin installed in your plugins area, Are you having more than one AMP plugin? because you only need one AMP plugin on your website and if you have more than one then it will show error.

And will you please share your wp-admin credential on team@magazine3.com and we will install our AMPforWP plugin on your end and we will make sure it will work perfectly,

**Comment by khurram55pk** [comment]
email sent on team@magazine3.com please check

**Comment by Zabi09** [comment]
Fixed in #2762 so closing this one.
