### ISSUE TITLE
Need to make compatible with WP Appbox.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2791]
Need to make compatible with WP Appbox.
Ref : https://secure.helpscout.net/conversation/747247418/48667?folderId=2322652

**Comment by MARQAS** [comment]
Data is coming, we just have to style the data.

**Comment by pegazee** [comment]
- [ ] We need to add the background image of the appbox. Screenshots:
non-amp: https://take.ms/yZ2z2
amp: https://take.ms/CrOkl

- [ ] On mobile mode, non-amp looking like this: https://take.ms/iFmYd and amp:https://take.ms/42StS. We need to make like the non-amp style.

- [ ] We need to show the stars like in non-amp ( Screenshot: https://take.ms/rccPe ). And in amp, it's not showing ( Screenshot: https://take.ms/ZX7ov )

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
escaping is missing 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5a548f36c3ba525a8a34f6883c81df4ca94e82ca#diff-1301281de287d2aed98746fc9ba777b4R764

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.45

**Comment by hmzisb** [comment]
It doesn't work for me. I am getting "The site is experiencing technical difficulties." When I access the site with ?amp. 
Non-amp version of post works fine. The plugin is working for all posts where WP-Appbox is not used. 
I checked the log file but I there isn't anything. (Tested with several posts)
Any clue?

**Comment by hmzisb** [comment]
Got error log. The issue is caused by Advanced ads pro. Any fix?

[24-Aug-2019 10:24:54 UTC] PHP Fatal error:  Uncaught Error: Call to a member function output_content_links() on null in /home/sitename/public_html/wp-content/plugins/advanced-ads/classes/ad_type_plain.php(124) : eval()'d code:1

Stack trace:
#0 /home/sitename/public_html/wp-content/plugins/advanced-ads/classes/ad_type_plain.php(124): eval()
#1 /home/sitename/public_html/wp-content/plugins/advanced-ads/classes/ad.php(555): Advanced_Ads_Ad_Type_Plain->prepare_output(Object(Advanced_Ads_Ad))
#2 /home/sitename/public_html/wp-content/plugins/advanced-ads/classes/ad.php(293): Advanced_Ads_Ad->prepare_frontend_output()
#3 /home/sitename/public_html/wp-content/plugins/advanced-ads/classes/ad-select.php(122): Advanced_Ads_Ad->output()
#4 /home/sitename/public_html/wp-content/plugins/advanced-ads/classes/ad-select.php(101): Advanced_Ads_Select->get_ad_by_id(Array)
#5 /home/sitename/public_html/wp-content/plugins/advanced-ads/classes/ad_placements.php(340): Advanced_Ads_Select->get_ad_by_method(1357, 'id', Array)
#6 /home/sitename/public_ht in /home/sitename/public_html/wp-content/plugins/advanced-ads/classes/ad_type_plain.php(124) : eval()'d code on line 1
