### ISSUE TITLE
Image size smaller than recommended size

### ISSUE THREAD

**Issue by pra85** [ahmedkaludi/accelerated-mobile-pages#2814]
Got the following AMP Warning which affected nearly all the AMP pages.

![Google Search Console AMP Warning](https://i.imgur.com/puI3IgR.png)

This is likely happening because of the image dimensions not meeting the guidelines in https://developers.google.com/search/docs/data-types/article#article_types. 

Is there an option to change the featured image dimensions via the plugin?

**Comment by MARQAS** [comment]
Hi @pra85, 
First of all, this is just a WARNING. It is NOT an error. AMP pages will still get indexed and displayed in Google’s search results. However, they are marked as less than perfect pages, because they contain images which are less than 1200 pixels wide. And This is not our plugins problem, it’s just one of the Google new requirements.

According to Google, Below are the Image required properties:
* Images should be at least 1200 pixels wide.
* Every page must contain at least one image (whether or not you include markup). Google will pick the best image to display in Search results based on the aspect ratio and resolution, etc.

You can read more from here: https://developers.google.com/search/docs/data-types/article#article_types

Coming to the solution, We’re still trying to figure out how to fix this issue permanently without having to change the existing featured image. 
The temporary solution can be to select the featured images which are 1200px wide or more.

**Comment by MARQAS** [comment]
We are closing this ticket until we find a better solution.

**Comment by MohammedKaludi** [comment]
This issue was fixed in Image size smaller than recommended size Warning in Search console #2838
