### ISSUE TITLE
Need to create an option link to non-amp under breadcrumbs when Archives support is off.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2885]
Desc: Need to create an option link to non-amp under breadcrumbs as a child option and should be visible when Archives support is off which will redirect to the non-amp categories pages.

screenshot: https://monosnap.com/file/mSnxit1UgOxuMFxVbHvM8zbz6777YQ

Ref: https://secure.helpscout.net/conversation/767895198/53616?folderId=2169248

**Comment by MARQAS** [comment]
It is working as expected. 
When archives support is off the archives links are going to non-amp.
We have already resolved this issue some time ago. 
Please do check with the user and asks him which version he is using and where exactly he is having this issue.

**Comment by jpaon** [comment]
I am that user, and the issue is not resolved. It looks like it's misunderstood by syedimran22.  I am using the latest version that is available for your plugin. I am having two issues. I see the screenshot syedimran22 posted that I have access to was for a breadcrumb archive.  This is not a breadcrumb category amp non-amp issue.

Look at the demo design for theme 3 that you have located here [https://ampforwp.com/demo/three/what-shakespeare-can-teach-you-about-review/amp/](url)

It says "Published by Ahmed Kaludi in Category 1 Uncategorized"

The only way to have category 1 and uncategorized be clickable links is if they link to AMP pages.  The same goes for tags.  At that bottom of that page, you have the tag "lead generation."  If AMP support for Archives [Category & Tags] is disabled in the plugin's menu, the category links and tag links that I just pointed out cannot be clicked on.  I don't understand why those links only work if AMP support is enabled for category and tag archives.  I do not want that.

**Comment by MARQAS** [comment]
Not working as expected, need to improve the code.

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/184394c99f7d915baf8f7f3c7051d21a6359dd99#diff-897b437f30bbe166b4ee44d85c167beaR21,
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/184394c99f7d915baf8f7f3c7051d21a6359dd99#diff-897b437f30bbe166b4ee44d85c167beaR19
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/184394c99f7d915baf8f7f3c7051d21a6359dd99#diff-1c658a072a9aabbdb42ca7c2d0972b8bR19
and more places esc_html, esc_attr
 use escaping while print

**Comment by ajeetku** [comment]
Make sure all escaping are properly make sure with master & some places escaping also not added in master

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
need to discuss about this issue.

**Comment by MohammedKaludi** [comment]
`!empty()` check needs to improve 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9f39cc10f7810e622efb390ffe1157a69c431d15#diff-897b437f30bbe166b4ee44d85c167beaR29

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
