### ISSUE TITLE
Link to tags & categories are wrong

### ISSUE THREAD

**Issue by aleemahmed2003** [ahmedkaludi/Accelerated-Mobile-Pages#292]
Hi,

I’ve noticed that the links to the categories & tags on the posts are wrong, they are redirecting to the post himself.
For example: http://www.recyclart.org/2016/11/christmas-tree-made-citizens-2200-recycled-plastic-bottles-elbasan-albania/amp/
the tags are redirecting to: http://www.recyclart.org/2016/11/christmas-tree-made-citizens-2200-recycled-plastic-bottles-elbasan-albania/amp/?amp instead of example (tag) http://www.recyclart.org/tag/recycled/?amp
Any idea how to resolve this issue?
Thanks,

2.I have the latest version of your plugin, downloaded 2 days ago directly from wordpress repo.

https://wordpress.org/support/topic/link-to-tags-categories-are-wrong/#post-8551671
Reported by @recyclart

**Comment by ahmedkaludi** [comment]
The problem is still in the latest version 0.9.1.1 but I’ve found the issue.
For the cat you are using: $cat->term_taxonomy_id which is not good, you should use $cat->term_id
Now the link is good.
Same for the tags, you are using $tag->term_taxonomy_id which is not working, but by using $tag->term_id everything work fine, all the links are corrects.
Hope this help.
