### ISSUE TITLE
Warning: date() expects parameter 2 to be long, string given in

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2959]
Warning: date() expects parameter 2 to be long, string given in /home/hmotahari/public_html/blog/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 199

Ref:  https://secure.helpscout.net/conversation/796649512/58519?folderId=1914712

Updated code:  `'dateModified' => date ( 'c', strtotime($post_modified_timestamp )),`

**Comment by MARQAS** [comment]
Why are we making this change? 
Previous code: 
datePublished' => date( 'c', $post_publish_timestamp ),				
'datePublished' => date( 'c', get_the_date( 'U', $post->ID ) ),
 
New code: 
'dateModified' => date( 'c', $post_modified_timestamp ),				
'dateModified' => date( 'c', get_the_date( 'U', $post->ID ) ),

but we are already taking `$post_publish_timestamp = get_the_date( 'U', $this->ID );`

I guess the issue is with the post_id or maybe settings of the user?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
update the code on the top instead of only updating on the call

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/0.9.98/includes/vendor/amp/includes/class-amp-post-template.php#L178

**Comment by MohammedKaludi** [comment]
:+1: ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
