### ISSUE TITLE
AMP Page Builder not showing on post and pages

### ISSUE THREAD

**Issue by cappaul123** [ahmedkaludi/accelerated-mobile-pages#3015]
Hi,

We are using avada with fusion builder and the AMP page builder is not showing in page and post editor.

Thanks.

**Comment by RajuJeelaga** [comment]
please contact https://ampforwp.com/support/ our technical support team will help you with it.

**Comment by Zabi09** [comment]
@cappaul123 
Have you enabled AMP page builder option - https://prnt.sc/nfsivy
We tried to recreate your issue on our end but it is working fine.
Will you please contact us on team@magazine3.com and we will help you in fixing your issue.

**Comment by Zabi09** [comment]
@cappaul123 
Have you contacted us? Because I have checked all our emails but unable to see your message and I have tested again but it is working fine.
Edit page - https://prnt.sc/ng6nax
Non-AMP output - https://prnt.sc/ng6nkx
AMP output - https://prnt.sc/ng6nv0

Please contact us on team@magazine3.com and we will help you

**Comment by Zabi09** [comment]
Unable to recreate the issue and the user is not responding so closing the ticket and if anyone has the same issue then please contact us on team@magazine3.com and our team will help you
