### ISSUE TITLE
Menu text  are overlapping and making the arrow unclickable in mobile version

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3099]
Ref:https://secure.helpscout.net/conversation/837679740/64064?folderId=2770543

Screenshot: https://monosnap.com/file/lik7Te6xq3yLtIvbB0BK7xtc57Rjwp

**Comment by RajuJeelaga** [comment]
Reference Link : https://www.injectorrx.com/

**Comment by MohammedKaludi** [comment]
Very strange issue we are not able to recreate the issue locally. And this happening as a very rare case.

Reference:

Issue fixed by adding this css in custom css area.
`.m-menu .amp-menu  li {
   color: rgba(255,255,255,0.8);
   padding: 12px 7px;
   margin-bottom: 0;
   display: inline-block;
   width: 100%;
  }
  .m-menu .amp-menu  li a{
   padding:0;
   }
  .m-menu .amp-menu .toggle:after {
   font-size: 20px;
   padding: 0;
   }`
