### ISSUE TITLE
code appears on top of every page after plugin activation

### ISSUE THREAD

**Issue by Bibi40k** [ahmedkaludi/accelerated-mobile-pages#3189]
AMP 0.9.97.51.2

![Screenshot 2019-05-15 at 13 59 08](https://user-images.githubusercontent.com/4104609/57770735-a6edc980-7719-11e9-9e18-ba3331f44d4c.png)

**Comment by ahmedkaludi** [comment]
@Bibi40k can you please send me the url and the WP admin details on ampforwp.com/support ?

I'll immediately have a look and fix it for you

**Comment by Bibi40k** [comment]
I'm sorry, i can't. It's a business account... Is there another solution ?
Any idea to start with ?

**Comment by ahmedkaludi** [comment]
We can do a Skype video call? And you can show me the bug which will help me understand

**Comment by Bibi40k** [comment]
Sure, Skype would be perfect, what is your id ?

**Comment by ahmedkaludi** [comment]
My Skype is Matt.kaludi

**Comment by pegazee** [comment]
@Bibi40k, The issue is coming from your custom code of child theme. To resolve the issue, you can contact our technical team they will assist you & resolve the issue on your end. You can contact here: https://ampforwp.com/support/

Note: Please attach this thread or URL in the email. so that our team members will easily resolve the issue.

**Comment by Bibi40k** [comment]
pk, thank you
