### ISSUE TITLE
 Problems with wordpress 5.2 update

### ISSUE THREAD

**Issue by Abel1011** [ahmedkaludi/accelerated-mobile-pages#3210]
I made the update to wordpress 5.2 and the plugin amp to the latest version and I got Server Error (5xx); did not enter the amp pages. I had to return to the previous version of wordpress and the plugin to work again.

**Comment by ahmedkaludi** [comment]
@Abel1011 Can you please send me the WP-admin information via https://ampforwp.com/support/ ?

I will personally help you fix this issue for you.

**Comment by MohammedKaludi** [comment]
We have just pushed an update that fixes few issue related to the one you have mentioned.

So I suggest you to update the plugin to the latest version and if the issue persists then please do let us know.

Here is the list of all the issues that have been fixed in latest update


Changelog
0.9.97.53 (20TH MAY 2019)
Fixed: 500 errors on posts that don’t use WP Bakery #3183
Fixed: Hyperlink in amp pages including emoji – code improved #2967
Fixed: Errors in AMP social Icons #3033
Fixed: Code improved to fetch all Categories and tags in Featured Slider [Design -3] #2590
Fixed: Fatal error on posts with comments present in latest v0.9.97.52 #3191
Fixed: “View Desktop Version” feature is not working in mobile view #3192
Fixed: Improved the Extension array code #3206
Fixed: Fatal error Uncaught TypeError Argument 1 passed to DOMNode::replaceChild() #3203

**Comment by ahmedkaludi** [comment]
@Abel1011 Please update us about this issue

**Comment by Abel1011** [comment]
Hi guys, I just tried again. First I updated the wordpress without updating the plugin: AMP worked normal.

Then I updated the plugin to the latest version and got the following message when loading the AMP: "The site is experiencing technical difficulties"

**Comment by Abel1011** [comment]
I am currently working with the version of wordpress 5.2.1 and the version of AMP 0.9.97.50.1 to make it work normally

**Comment by ahmedkaludi** [comment]
@Abel1011 If you need help, then you have to contact us via https://ampforwp.com/support

**Comment by Abel1011** [comment]
Hello dear. One last question, what information should I send through the form so that you can analyze the problem and help me with the solution.

**Comment by ahmedkaludi** [comment]
@Abel1011 WP admin credentials

**Comment by lantcnl** [comment]
Hello, I think I'm having Server Error (5xx) too.  I noticed this week the message "The site is experiencing technical difficulties" when loading the AMP version. I had to disable the plugin because of that.
Any help?

**Comment by ahmedkaludi** [comment]
@lantcnl  Can you please send me the WP-admin information via https://ampforwp.com/support/ ?

I will personally help you fix this issue for you.
