### ISSUE TITLE
Clicky Analytics option need to implement

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3220]
- [x] Clicky Analytics option need to implement in the Core.

- [x] When the option is implemented in the core, need to do the change in the Tutorial based on the option
https://ampforwp.com/tutorials/article/how-to-add-clicky-analytics-in-amp/

**Comment by Zabi09** [comment]
Please change the position - https://prnt.sc/o5thv9

**Comment by MARQAS** [comment]
Use placeholder instead of the default: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e360349bc03b237429793eb44ca7325b7caee183#diff-8ada183a565e41de5b9a91a8047b98adR287

And also the analytics script is missing: `The tag 'amp-analytics' requires including the 'amp-analytics' extension JavaScript`

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
