### ISSUE TITLE
Debug errors after  0.9.97.60

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3377]
A new one, rarely seen in the logs, probably seen only when loading the admin plugins page:

PHP Notice: Undefined index: ampforwp-amp-on-off in /var/www/html/wp/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 809, referer: https://www.matthewsvolvosite.com/wp/wp-admin/plugins.php?plugin_status=all&paged=1&s

And the old ones remain:

[Thu Jun 27 10:37:09.746304 2019] [:error] [pid 9422] [client 108.162.246.79:30840] PHP Notice: Undefined variable: img_path in /var/www/html/wp/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php on line 135

[Thu Jun 27 10:30:20.533083 2019] [:error] [pid 9195] [client 108.162.221.121:64716] PHP Notice: Undefined offset: 1 in /var/www/html/wp/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php on line 124

REF: https://wordpress.org/support/topic/apache-logs-full-of-php-notices/#post-11679487

**Comment by lezama** [comment]
I am getting this one too:

[28-Jun-2019 19:25:14 UTC] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'ampforwp_menu_transient_on_save' not found or invalid function name in /home/migueluy/public_html/wp-includes/class-wp-hook.php on line 286

**Comment by pegazee** [comment]
@lezama 

I'm trying to recreate the same issue on my local server but it's not created. May I know how to re-create this issue?

**Comment by lezama** [comment]
I can't reproduce again 😞 , somehow I got that one during the setup process.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
> I can't reproduce again 😞 , somehow I got that one during the setup process.

But is it still throwing an error? And whats the current status?

[28-Jun-2019 19:25:14 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ampforwp_menu_transient_on_save' not found or invalid function name in /home/migueluy/public_html/wp-includes/class-wp-hook.php on line 286

The error throws due to add_action does not finds the callable function in this scenario we are referring to this function `ampforwp_menu_transient_on_save`

But as i see the function is available  and I think there is no warning showing at present, then I think we can ignore this.

But if you are still getting the warnings in debug then we can dive deep and find more info about this.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
