### ISSUE TITLE
AMP plugin executes the shortcode when placed with double brackets (i.e., [[shortcode]]) but it should not execute them.

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/accelerated-mobile-pages#3481]
https://secure.helpscout.net/conversation/909343729/74949?folderId=3004564

**Comment by MARQAS** [comment]
No solution has been added

**Comment by MARQAS** [comment]
The issue still persists. Check below for AMP and Non-AMP version.
AMP: https://monosnap.com/file/3NlTvbiCtjj9QqZ4DMaL2jOoKWxABD
Non-AMP: https://monosnap.com/file/EHL3suGtpAr79xeYlBbzzgUrkem1Kz

Please understand the issue, when someone adds the shortcode with one more set of brackets, it should not execute the shortcode. 
For example: If a person adds something like this `[[gallery ids="294,295,272,270"]]` then it should look like this `[gallery ids="294,295,272,270"]` instead of the gallery itself.

**Comment by MohammedKaludi** [comment]
Fix working in 99-beta branch but not working with .98.5 branch.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
