### ISSUE TITLE
New UX for AMP Options Panel

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3520]

**Comment by Zabi09** [comment]
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at new Drawer (admin-script.js?ver=0.9.98:1161)
    at admin-script.js?ver=0.9.98:1126

**Comment by RajuJeelaga** [comment]
After Discussion with Ahmed sir, some improvements in the AMP option panel

### Improvement List in AMP Option panel

- [ ] when we click on the settings section default tab will be General, need to remove the content 
https://monosnap.com/file/dSgoPcu3Hgz8hp6nzCm3XHzdt1dmlm
Ref: Check the Design section, Default Tab is Global,

- [ ] https://monosnap.com/file/ADdcWBtNcKrp8nvjfEH7Tv75GILq0u

- [ ]

**Comment by Zabi09** [comment]
- [ ] Website type of News and Blog is not working - https://prnt.sc/pf7ixm because the names are different in structured data - https://prnt.sc/pf7j9w
- [ ] added logo from the easy setup - https://prnt.sc/pf7qf0 and it is not working - https://prnt.sc/pf7qkt (image is appearing in source code but the width and height are empty)
- [ ] Need to improve the radio of inactive section - https://prnt.sc/pf7832
- [ ] Borders are missing - https://prnt.sc/pf7ajf (appearing fine in master)
- [ ] Archives support should be on by default - https://prnt.sc/pf7b2s
- [ ] We need to remove the search icon from easy view - https://prnt.sc/pf7kyb
- [ ] Do we need this banner now - https://prnt.sc/pf7lgh because we are already added here - https://prnt.sc/pf7lk5
- [ ] Analytics Tracking should only show one analytics which the user is currently using - https://prnt.sc/pf7t18
- [ ] Only one analytics is working which we have added here - https://prnt.sc/pf7vb0
If someone added google analytics first from easy view then added facebook pixel then only facebook pixel analytics is showing up without google analytics
- [ ] If there is no SEO plugin then also it is showing Yoast - https://prnt.sc/pf77pq

**Comment by RajuJeelaga** [comment]
### Finali List

- [ ] We need to remove the search icon from easy view - https://prnt.sc/pf7kyb [wasim]

- [ ] Do we need this banner now - https://prnt.sc/pf7lgh because we are already added here - https://prnt.sc/pf7lk5 [wasim]

- [ ] When Easy view is selected, the below items should not load/display. [Wasim]
https://monosnap.com/file/z7rAkTB7oFeHGRKikN6H7KVK1l9vfo

- [ ] Internal options of the website dropdown names [Ahmed sir]
https://monosnap.com/file/Ngkzkhgby3oHsXTBr0YmPjErzSYrqx

- [ ] slide jumping problem [Wasim]

- [ ] Analytics saving issue [Wasim]

**Comment by ahmedkaludi** [comment]
- [ ] after the update only once, the cookie should be removed because it takes the people to a strange page. https://monosnap.com/file/5yvPjc69iZTj824UQ2ktXQBOrm4N5M

- [ ] New user vs Old user update, what happens, we need to discuss and clear this. 

- [ ] need to remove this: https://monosnap.com/file/i6ihCfmTPcS6eV5SjrAfI10RQkAQpp

**Comment by Zabi09** [comment]
- [ ] When I selected blog posting or news article in master then it should automatically appear here also - https://prnt.sc/pjzaze now it is showing "other" as default
- [ ] When I selected the custom frontpage in master then it is not appearing here - https://prnt.sc/pjzcsc
- [ ] After the setup is done once I refresh the page this is still showing up - https://prnt.sc/pjze9l

**Comment by RajuJeelaga** [comment]
- [ ] if I am a user that have "Newsarticle" schema setup, after the UX update, what will happen to my schema?

**Comment by Sanjeevsetu** [comment]
- [ ] After changing website type to other, Value is not being changed in drawer website option. ( prnt.sc/pkw48b )

**Comment by ansaritalha** [comment]
- [ ]  after activating ads for wp plugin and choosing a full options view then the advertisement section is blank,it's better to have a link to redirect on ads for wp setting panel.

**Comment by ansaritalha** [comment]
- [ ]  after activating ads for wp plugin and with full options view mode advertisement section showing as blank, it's better to have a link to the redirection on ads for wp setting pane.

- [ ] same issue mention by @Sanjeevsetu related to 3rd party view button.

- [ ] website type "other" is working as expected to me.

**Comment by merajali294** [comment]
- [ ] On first installation it gives disturbing design(chrome-extension://fdpohaocaechififmbbbbbknoalclacl/capture.html?id=4&url=http%3A%2F%2Flocalhost%2Fwordpress%2Fwp-admin%2Fadmin.php%3Fpage%3Damp_options%26tab%3D1)

**Comment by Rkroy** [comment]
- On the first click to the settings area, saving option is not showing, please check the video.
https://monosnap.com/file/NuevSvVtcA6dEyR6d75lEZJmsbN0sy

- By default structured data is empty unless we click on the toggle, we need to show some content by default.
https://monosnap.com/file/IIEjuDAtqb8nhXkHSyCxoorYlIj6jv

- If we select any other themes, then the AMP layouts section not be shown.
https://monosnap.com/file/KfAq6LHmutbhriuCk41dj8CUBaYgRg

- In the AMP layouts section, the layouts view is breaking, in the first few rows it is showing 2 blocks, and in the last row, it is showing 3 blocks.
https://monosnap.com/file/bEd5pIC9xAkAzAFSxkU1hex9MGfWH5

- Wastage of area in the menus section.
https://monosnap.com/file/CzcenvzGw7R7I8SWJNpFU1Rhdpi6ZE

- On Easy Setup View, we can add an option to change the logo and we can also give feedback to the user that the logo has been updated, because when I uploaded the logo I was not sure whether it has been saved or not unless I check the frontend.

- On Easy Setup View, textarea and dropdown looking awful, if we can improve then it'd look better.

- On Easy Setup View, We are listing our own plugins as third-party compatibility?
https://monosnap.com/file/pbqKcIBMnDKF1ljMq5ONvHfRaUljRq

- On Easy Setup View, when we click any of the plugin setting icons, and if the plugin is off then it automatically turns on the plugin and on next load it redirects to the settings area of the respective plugin, so as a user we're unaware what is it doing in the background, so if we can show some details to the user it'd be better.

**Comment by sonaliramteke** [comment]
- [ ] When we turn of Archive support in setup then it's not changing in general tab

**Comment by syedimran22** [comment]
- [ ] On Easy Setup when we are hovering AMP  options then Settings and design options are visible.

- [ ] AMP Layouts title is renderring in Design1,2,3 (https://prnt.sc/pkxkhx), which should be visible only in swift.

- [ ] Need to discuss about template mode options regarding extensions

**Comment by akashagrjsr** [comment]
- Need to fix sub menu issue in design one, two and three
Ref: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3428

-Save button disappearing after changing the theme. 
  If we switch from setup to design then the save button is not showing. 
  Screenshot:https://monosnap.com/file/lMEonMT1RNAVFyJulpjEsQRKK4Jsom

**Comment by santosh8793** [comment]
- [ ] Options data is not getting reflected in settings tag panel as we change in Setup panel like Wedsite Type , Where do you need AMP for Archive(option) 
- [ ] Advertisement section is blank
- [ ] Analytics Tacking in Setup Analytics Tracking popup close button not working
- [ ] Save changes button at the bottom of option panel is not showing

**Comment by Arihantkankariya09** [comment]
1. In Design and presentation tab:- When a logo is already been added, there should be a "Change logo" or "Remove logo" option.
https://monosnap.com/file/356KoHTp9cxVTyI58RvRUWz0PINeBU

2. In the Privacy settings tab:- When Cookie Notice bar is enabled GDPR gets disabled and vice versa
https://monosnap.com/file/DZFQpxOt3qZLpr1lixRb8ADza7F1AJ
In previous versions, both can be enabled simultaneously.

**Comment by TMsravan** [comment]
- [ ] Need to adding padding : https://monosnap.com/file/wYWN9Y5EAGmDAtIoOYdIUcHDQGaMHw

**Comment by amer07** [comment]
- [ ] In full setup view  Advertisement section is blank
Screenshot:https://prnt.sc/pl0avp

- [ ] In Easy setup 3rd party compatibility option text is not showing on the button.
Screenshot: https://prnt.sc/pl07tz

**Comment by SayyadF** [comment]
1. In setting>general save setting some time option is not showing.
https://monosnap.com/file/CX3JkA57jHwcJ4E3ViO0mJpWG5GkKv

2.If GDPR is enabled then color should be kept as "white" not green.
https://monosnap.com/file/D3KNrVsXFvNucmqjMZPggx7KKPIuZY

**Comment by TMsravan** [comment]
- [ ] In Select Categories to Hide AMP field: a tooltip is not aligned in the center.
Ref: https://monosnap.com/file/byrdBZnKtPoK2gFE7m3rgaKeZxpliB

- [ ] In full option view section: Advertisement section is blank.
Ref: https://monosnap.com/file/trExDteEQyQSbuyE0JRrAjTxEnKCMv

**Comment by Thakur25** [comment]
- [ ] In the setup,if we select types of website, we do not get a placeholder for writing the website 
       type. we only get this option in "Others".
       Ref: https://monosnap.com/file/Z9kLLe37I6A8kPouYtyRecNW4IzB4a
       Ref: https://monosnap.com/file/JxVDXUFYi8dh8pw7axtBlcSxbCu2uD

**Comment by wankhedekomal** [comment]
- [ ] In Structured data field when we focus on category field a horizontal scrollbar is coming.

same thing is happening in tools field also.

https://monosnap.com/file/Ks5vIyTdYUIXr43hJom4LVJBCLGCdg

**Comment by sardarui** [comment]
Everything is working fine with an attractive interface and I have noticed a blank screen in the advertisement section which is already reported by Sravan and Amer.

**Comment by nommanshaik18** [comment]
In Easy Setup View mobile redirection option is not the there as it is for mobile after doing setup user will get confused when checking

**Comment by MohammedKaludi** [comment]
Escaping missing:
1. https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-8a5026375ec4a4a59b1d9d846beba869R182

2. https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-8a5026375ec4a4a59b1d9d846beba869R233

3. https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-8a5026375ec4a4a59b1d9d846beba869R253

4. https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-8a5026375ec4a4a59b1d9d846beba869R255

5. https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-8a5026375ec4a4a59b1d9d846beba869R257

6. https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-8a5026375ec4a4a59b1d9d846beba869R266

7. https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-8a5026375ec4a4a59b1d9d846beba869R276 


Also at many other places

**Comment by MohammedKaludi** [comment]
Escaping missing: 
1. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2b4fb467c0d7579539cd142b4c312b01ed1a81b1#diff-8a5026375ec4a4a59b1d9d846beba869R319

2. `'.esc_attr($this->selected).'>';` escaping here will break the attribute.

 `$this->selected = $this->default ? 'value='.esc_attr($this->default) : "";`
`$output .= '<input type="text" id="'.esc_attr($this->id).'" class="'.esc_attr($this->class).'" '.esc_attr($this->selected).'>';`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2b4fb467c0d7579539cd142b4c312b01ed1a81b1#diff-8a5026375ec4a4a59b1d9d846beba869R401

**Comment by MohammedKaludi** [comment]
Escaping still missing:

https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-260eba6333c3222e59a6aed22ac5ab37R1291

And we have lot of items that are unescaped below.

https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-16fe4bbd7bfcb2a48a50e91d89c63d14R66

Remove unused function
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-1b98edde9332a5e4649db583249c268bR27

Check if the current user has the permission to manage the options or not
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7197

Remove unused code.
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3794/files#diff-68ba1c10ce82621c3a0617130084e88cR34

**Comment by MohammedKaludi** [comment]
Code is ready, need the testing once again to make sure everything is working as expected.

**Comment by Zabi09** [comment]
https://prnt.sc/pnz78a

**Comment by RajuJeelaga** [comment]
on Safari Browser, AMP option panel is not working and the design is breaking as well and on click element section the overlay is not responding,
https://monosnap.com/file/6ZLI2KAY2YXMCFDvCrbRcGWrFUDMOD

Note: We need to do AMP Option panel Compatibility for the Safari Browser, and
in the coming updates we need to release this based on the priority.

**Comment by MohammedKaludi** [comment]
No options panel in the latest version of safari https://take.ms/olJr4

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.15 update

**Comment by MohammedKaludi** [comment]
One ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1695bb1742b51073390360d00dee851a50e63da3

**Comment by akashagrjsr** [comment]
- [ ] Change Label of Activate This module for PWA as Activate this plugin.

Screenshot: https://monosnap.com/file/T2ewEyCOdbCaTZ2AhOEvASqGrd9EDJ
