### ISSUE TITLE
"Recent Posts below related posts" feature need to implement for the design three

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3531]
Screenshot: https://monosnap.com/file/dSnCMlAAwheqeLniDqU2krnzTRPKgT

Ref: https://secure.helpscout.net/conversation/919523294/77306/

We need to add a "Recent Posts below related posts" feature for the design three themes. Currently, this feature is available for the Swift theme only.

**Comment by Zabi09** [comment]
Please use ampforwp_get_setting in place of $redux_builder_amp and also date is looking large please make it smaller - https://prnt.sc/oy60ny

**Comment by Zabi09** [comment]
The permalink is incorrect and also it should be off by default.

**Comment by Zabi09** [comment]
Still not working, Will you please check once

**Comment by MohammedKaludi** [comment]
1. Position of the control is incorrect https://take.ms/y0UXS
2. Remove validation as it creates some problem when saving datahttps://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e9d94396d0c6af45d4b3e77693705467bf26f3e5#diff-260eba6333c3222e59a6aed22ac5ab37R6402
3. use `ampforwp_get_settings` instead of `$redux_builder_amp['something']`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
