### ISSUE TITLE
Need to add the addthis share button's postion field in design1,design2,design3

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3553]
Ref: https://secure.helpscout.net/conversation/917793081/77113?folderId=2632030

https://monosnap.com/file/LbArDlOCYGQmzlqCLuYYEliz3FcZlk

**Comment by MARQAS** [comment]
Commented part can be helpful when Order of Elements ticket is released.

**Comment by MohammedKaludi** [comment]
@wasimmagazine3 can you please let me know, Why this filter was removed ? 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/79d6cc1e3f3dd26e9074d3935f3346be070ce01a#diff-caeb2e54b33d2d164c9e50b9731eb751R13

**Comment by wasimmagazine3** [comment]
@MohammedKaludi As we have the positioning of AddThis share buttons in design1, design2, and design3 now. Previously we do not have the positioning for social icon and it was at the fixed position. So after adding the option for addthis positioning it was showing two social share icon one was with AddThis positioning and another was outside of the element that's why I commented those two line code.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.6
