### ISSUE TITLE
Incorrect title tags being generated

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3565]
AMP for WP 0.9.98.4 using design 2 in AMP takeover mode – The plugin is no longer using the meta <title> as defined in Genesis on the front page nor any of the inner pages. This was fixed in the previous version but the bug has come back. It is simply using the page title and not what is defined for the meta.

https://wordpress.org/support/topic/incorrect-title-tags-being-generated/#post-11840819

**Comment by Frenchomatic** [comment]
Just sent you screen shots and login info so you can see what is happeneing. If you need FTP then email me.

**Comment by Zabi09** [comment]
Commit ref: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c66e8fee863a599be784bb812463efb3e71d121b

**Comment by Frenchomatic** [comment]
Excellent news. The site I sent you is now functioning correctly. However, something a bit strange. When I just use the files from github on another web site whcih had this problem (identical setup)  it creates problems where you can no longer edit pages in admin. If I copy the whole of your plugin from the site that you fixed to the one which doesn't, it then starts to function correctly.  Does #c66e8fe contain all of the necessary edits / changes? It is probably worth checking.

**Comment by Zabi09** [comment]
Yes you can change only https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c66e8fee863a599be784bb812463efb3e71d121b and it will also work on your other websites

**Comment by Frenchomatic** [comment]
OK - it didn't for me. I had to copy the whole plugin so perhaps something was different or perhaps it was because the plugin needed to be deactivated  / reactivated. Anyway, all is now working  - thanks




On 23 Aug 2019, at 09:20, Syed Zabiuddin <notifications@github.com> wrote:

Yes you can change only c66e8fe <https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c66e8fee863a599be784bb812463efb3e71d121b> and it will also work on your other websites

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.6
