### ISSUE TITLE
Not compatible with vc

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#381]
the plugin conflicts with Visual composer and only shows the shortcode.

**REF:**https://wordpress.org/support/topic/error-shortcode-visual-composer/

**Comment by Lofesa** [comment]
@MARQAS to erase all shotcodes from visual composer I have added these line in templates/features.php

function ampforwp_the_content_filter( $content ) {
                                 $content = preg_replace('/\[[\/]?vc_(.*?)\]/', '', $content);

The line must be the 1st, because if not they don´t work well, I don´t know why.

Another aproach to this (and all others shortcodes) can be the use of [do_shortcode()](https://developer.wordpress.org/reference/functions/do_shortcode/), but you must deal whith all the html code generated by that

**Comment by khaledMohammed000** [comment]
Hey @Lofesa 

I need a small help, could you please download the code from branch https://github.com/ahmedkaludi/accelerated-mobile-pages/tree/0.9.33 and test the VC posts that were not working....please dont use the code 

> $content = preg_replace('/[[/]?vc_(.*?)]/', '', $content);
 
Directly use the code from the branch https://github.com/ahmedkaludi/accelerated-mobile-pages/tree/0.9.33 and please test it and let me know 

If still the short codes are working or not 👍

**Comment by khaledMohammed000** [comment]
Any Update on this @Lofesa

**Comment by Lofesa** [comment]
Sorry for the delay
I have updated the plugin but I have modified it with the do_shortcode()
function.
But I tried it w/o the function and seems to work well.

2017-01-15 7:42 GMT+01:00 Mohammed Khaled <notifications@github.com>:

**Comment by MohammedKaludi** [comment]
Code working with VC tested by @Lofesa too
Closing the ticket
