### ISSUE TITLE
Thumbnail image of homepage should show properly after changing the image size

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3882]
Ref: https://secure.helpscout.net/conversation/1012530237/98980?folderId=1060554

Thumbnail images should show properly after changing the image size. The image aspect ratio is not proper.

Screenshot: 

1.https://monosnap.com/file/Y8fOLAImKDnSbBwyn3XV5MPImUNW4S

2. https://monosnap.com/file/MPCx2itN2dVXC6nUR7KtuwrjRvwtlu

Users scenario: User wants to resize the recent post's thumbnail images. The recent posts thumbnail image size is related to the homepage page thumbnail image, So we should take care of it.

**Comment by Zabi09** [comment]
Please use ampforwp_get_setting function

**Comment by Zabi09** [comment]
Not working in vertical and carousel designs - https://prnt.sc/q5lx9z

**Comment by MohammedKaludi** [comment]
1. This is not connected with image height/width fix. https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/design-manager/swift/single.php#L353


2. `ampforwp_get_relatedpost_image` why not improve the this function instead of replacing it with `amp_loop_image()` or if `amp_loop_image()` is better interms of performance or both are the same functions then remove the unused function.

**Comment by MohammedKaludi** [comment]
Are we sure we have taken the users issue into account?
Users scenario: User wants to resize the recent post's thumbnail images. The recent posts thumbnail image size is related to the homepage page thumbnail image, So we should take care of it.

**Comment by MohammedKaludi** [comment]
`ampforwp_change_related_post_size ` 
incorrect filter name: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/287cbcb56f881620179ec97d10949d0a7195c2bb#diff-4df5c887c9bf062e619962dc7e2c804eR154

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
