### ISSUE TITLE
The Alternate Menu does not redirecting to the AMP for the product category in menu items

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3915]
Ref: https://secure.helpscout.net/conversation/1018805340/100085?folderId=2770545

The Alternate Menu does not redirect to the AMP for the product category in menu items even after the user has enabled the "Auto Add AMP in Menu URL" option.

Steps to recreate:
1. Create some product categories.
2. Add these product categories in the menu items as sub-menus.
3. Enable the Dropdown support in the AMP option panel.
4. Enable the Auto Add AMP in Menu URL" option in AMP option panel.

**Comment by MohammedKaludi** [comment]
Instead of adding `$post_types['product_category'] = 'product_cat';` statically. 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/85cfc157a2db1fa5be5b3b335b87e2eea0e467d1#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1060


Get the selected Custom Taxonomy from the option panel : https://take.ms/50vv3

**Comment by MohammedKaludi** [comment]
need to add clear cache for footer menu and  Alternative menu.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/85ccda8a50b31e70529ab15704ca13c686c4f3bf#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1513

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2
