### ISSUE TITLE
Need to make compatibility with the Ultimate Addons For Gutenberg plugin

### ISSUE THREAD

**Issue by nakib4tech** [ahmedkaludi/accelerated-mobile-pages#3940]
Dear sirs,

The most needed features to make compatibility for is the buttons & multi button.

https://wordpress.org/plugins/ultimate-addons-for-gutenberg/

Cheers,

**Comment by nakib4tech** [comment]
I see the code is working, please merge it ASAP.
Because, the UAG plugin is breaking my layout in AMP.

**Comment by MohammedKaludi** [comment]
@nakib4tech it is in the testing phase, once it is tested we will push it in future updates

**Comment by MohammedKaludi** [comment]
@WasimM3 
few things needs improvement.
1. A fallback size for SVG https://take.ms/gXSlL

2. Function exists while adding the hook.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d8a03360d860f65621517fc48565ee2f38ab760e#diff-1301281de287d2aed98746fc9ba777b4R1077

3. use `class_exists( 'UAGB_Loader' )` instead of `function_exists('uagb_fail_php_version')`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Moved to https://ampforwp.com/compatibility/idea-board/
