### ISSUE TITLE
AMP Iframe Border Invalid

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#3954]
Same issue as here

https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3897

`<div style="position: relative; padding-bottom: 57%;"><iframe style="position: absolute; top: 0; left: 0;" src="https://gfycat.com/ifr/SimilarVainDragonfly" width="100%" height="100%" frameborder="0" scrolling="no" allowfullscreen="allowfullscreen"></iframe></div>`

TURNS INTO

`<div class><amp-iframe src=https://gfycat.com/ifr/SimilarVainDragonfly frameborder height=400 allowfullscreen class sandbox="allow-scripts allow-same-origin allow-popups allow-forms allow-top-navigation" layout=fixed-height><div placeholder class=amp-wp-iframe-placeholder></div></amp-iframe></div>`

Notice frameborder , it's empty and blank and causes google amp pages to invalide, all of our pages are now invalid

**Comment by djixas** [comment]
Update: the issue is due to latest W3 Total Cache plugin minify of HTML

**Comment by MohammedKaludi** [comment]
Hey @djixas,

This issue is with the latest version of W3 Total Cache and has been reported here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3871

Issue has been fixed and pushed in the latest update of AMPforWP plugin. 

Please update the plugin to 1.0.1 and do let us know if the issue fixed.

Rightnow, I'm closing the ticket. But Feel free to reopen if the issue persists after the update.
