### ISSUE TITLE
The implied layout 'CONTAINER' is not supported by tag 'amp-img'.

### ISSUE THREAD

**Issue by mrseth** [ahmedkaludi/accelerated-mobile-pages#425]
Keep getting:

"The implied layout 'CONTAINER' is not supported by tag 'amp-img'."

Any ideas? Thanks!

**Comment by ahmedkaludi** [comment]
Hey @mrseth Seth,

Can you please post the website URL where you are facing this issue?

**Comment by mrseth** [comment]
sure its https://ww.dexdog.com

Thanks

**Comment by mrseth** [comment]
any ideas? @ahmedkaludi

**Comment by ahmedkaludi** [comment]
@mrseth That's because the AMP-img tags doesn't have the height or width. The page builder is not outputting the format properly. See: https://validator.ampproject.org/#url=https%3A%2F%2Fwww.dexdog.com%2Famp%2F

I recommend you use the "Use AMP Content" from the post editor which will allow you serve a special AMP compatible content on the AMP version.

**Comment by shekankode** [comment]
This error occurs if we do not mention the width and height of an amp image. If the width and height attributes are not specified for an amp image (amp images must be given an explicit size as in width/ height in advance so that the aspect ratio can be known without fetching the image ), the inferred layout is container and so the error occurs.
