### ISSUE TITLE
Need to modify Onesignal Push Notification Option

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#4286]
Need to make the Switch turn to Select option and then we'll be adding one more support which is Izooto for AMP.

**Comment by MohammedKaludi** [comment]
Defaults are not properly setuped.

it makes blank for the previous version if One Signal is enabled  previously:

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f8df102296bf2a0d3dc7e57ab86af6eacbd03025#diff-df6930bf8e5dc30d1b50c8a71b6b22f6R100


`'3' => esc_html__('Select Integration Service', 'accelerated-mobile-pages' ),`

use `0` instead of `3` so those who have disabled Push Notifications in past, they will see `Select Integration Service` selection automatically.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
undefined warnings found: `$izooto_notice = $izt_opt1 = $izt_opt2 = $izt_opt3 = $izt_opt4 = ''; `


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/10a30f2eb72f3e520e3eac1a7a39f00a590b589b#diff-df6930bf8e5dc30d1b50c8a71b6b22f6R19

**Comment by MohammedKaludi** [comment]
Styling of child items are incorrect.

https://monosnap.com/file/UtGQAegG59zlyfy1pSChoFuiJJsRV6

**Comment by MohammedKaludi** [comment]
Ready to go.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.37
