### ISSUE TITLE
Related post images sizes issue with designs

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4302]
In related posts, different designs should have different sizes. However same size is being considered for all three design
Ref:
https://secure.helpscout.net/conversation/1105949267/116106?folderId=3611365

**Comment by Zabi09** [comment]
By following this tutorial - https://ampforwp.com/tutorials/article/how-to-change-related-posts-thumbnail-size/ he was changing the related posts size but we have renamed this filter - 'ampforwp_change_related_post_size' with 'ampforwp_related_post_image_size' due to that it was not working, so updated the tutorial for that and now closing this.
