### ISSUE TITLE
Date does not translate  in website native language on related posts.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4317]
Case 1: https://secure.helpscout.net/conversation/1108496332/116545?folderId=2770543
The date does not translate into the website's native language on related posts.
See this screenshot: https://prnt.sc/rn4tik

- [ ] 1.  1.  If the user is changing the format in his own language then he is not getting it in the output of related posts. He is only getting the English language.

See these screenshots: 
https://prnt.sc/rn4wei
https://prnt.sc/rn4wm8

- [ ] 2.We need to add tooltip of a question mark and link it with the article of the R.H.S
See this screenshot:https://monosnap.com/file/aLUKD69rMKXxykDyV6rHamvb6TuKkk

**Comment by Zabi09** [comment]
This is the issue of AMP layout so it will be fixed in that extension only

**Comment by aloumamae** [comment]
Hello, this issue is happening with my clients website: https://insidecenter.com.br - thats why Mohammed opened this ticket.

The date format on the design settings just define the order of the words... https://prnt.sc/rntxxa

The date format is good. and is displaying correctly on the website: https://prnt.sc/rntzzu

It is translated in the translation panel from the amp menu...

**Those are the texts that I am not being able to translate: https://prnt.sc/rntwx4**

How can I translate those?

Thank you
