### ISSUE TITLE
Disqus compatibility 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#437]
Disqus compatibility

**Comment by nicholasgriffintn** [comment]
The problem with this is it requires a script on a separate domain to work, with SSL, so support might be hard for a plugin since it would be hard to communicate:

https://github.com/disqus/disqus-install-examples/tree/master/google-amp

I reckon just adding an option to show a "View Comments" button that links to the normal article's comments would be better for now.

**Comment by Dibbyo456** [comment]
I would love it too

**Comment by MohammedKaludi** [comment]
@ahmedkaludi needs to update the path of our server
@khaledMohammed000 need to write a Doc on how to implement Disqus on AMP and need to add the link to the doc in https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/0.9.40/includes/options/admin-config.php#L1025

**Comment by ahmedkaludi** [comment]
This feature was properly added in the recent update
