### ISSUE TITLE
Need to create option for showing "Primary category"

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4495]
Need to create an option for showing only the "Primary Category".

URL: https://eleftherostypos.gr/oikonomia/579692-to-paketo-tsipra-fernei-mnimonio-moirase-lefta-poy-den-exei-to-kratos/amp/

Ref: https://secure.helpscout.net/conversation/1147737569/125224?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Breadcrumbs generating incorrect links

**Comment by MohammedKaludi** [comment]
Need to add the condition  like this: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6984b0a2f588956b97e784ddece9252a933b388e#diff-897b437f30bbe166b4ee44d85c167beaR28

here: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d1148972cbef3434f99cff7190deaedf8d090293#diff-d69695bf16addd334de42e22bef775c6R135


otherwise it will change to all the links everytime.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.62
