### ISSUE TITLE
Odnoklassniki sharing not working properly 

### ISSUE THREAD

**Issue by mmprep** [ahmedkaludi/accelerated-mobile-pages#4525]
Friends,

it seems that in order for you to somehow move to correct bugs I need to remind you of them repeatedly.

I have already contacted your technical support service: the button to share within Odnoklassniki does not work. Click and see for yourself. It is easy.

Thank you.

**Comment by syedimran22** [comment]
Hi @mmprep 
As you have mentioned that Odnoklassniki share button is not working so could you elaborate more by providing a link where the issue is occurring as it is a Russian social network and we are unable to access also it will helpful if there is any platform where we can test Odnoklassniki share button.

**Comment by mmprep** [comment]
Friends,
I don't really know what you want from me.
Does something prevent you from enabling the output of the Odnoklassniki button on your test site in the plugin settings and press it to make sure that it does not work?
Well, to make sure you can, for example, here [https://mosmedpreparaty.ru/news/20818/amp](https://mosmedpreparaty.ru/news/20818/amp)
Odnoklassniki API is here https://apiok.ru/en/ext/like

**Comment by syedimran22** [comment]
thank you @mmprep for sending the links we will check into it.

**Comment by WasimM3** [comment]
1. Please use `ampforwp_get_setting` instead of `$redux_builder_amp` 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/df3f3529690b294e9a370dd38c84ccf453ab801a#diff-9cbf83e0d21caa7d8505ed4a8d03b158R107

2. Please add escape this `ampforwp_rel_attributes_social_links`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/df3f3529690b294e9a370dd38c84ccf453ab801a#diff-9cbf83e0d21caa7d8505ed4a8d03b158R113

**Comment by MohammedKaludi** [comment]
Use smaller images, not full.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/df3f3529690b294e9a370dd38c84ccf453ab801a#diff-6aa5512f7dd8d5ce60fc97b0f340912cR1439

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
