### ISSUE TITLE
Need to implement change the image size for the related posts thumbnail

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4534]
Ref: https://secure.helpscout.net/conversation/1164869093/129784?folderId=2770545

We need to add option to change the image size for the related post thumbnail in the AMP option panel.

**Comment by WasimM3** [comment]
Please add escaping in the line and in other places likewise
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1c8c01dbd0eccf0ba0ba02795a1b38a7839104d8#diff-7d3a92ac5e6165548bf9bc556f4f887aR130

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/452d33d94adccc1514b07ee35091e439f8245eb8#diff-7d3a92ac5e6165548bf9bc556f4f887aL184

Incorrect code removed and not working with Retina images

**Comment by syedimran22** [comment]
Due to this code https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/design-manager/swift/single.php#L126,  #L127 and #L128 lines when retina image is set the image size are getting double of retina image size given so that we have to remove this code while merging this ticket during the update.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update
