### ISSUE TITLE
image was not loaded

### ISSUE THREAD

**Issue by adhackking** [ahmedkaludi/accelerated-mobile-pages#4617]
in my wp website in amp mode images was not loaded what shoud i do right now

**Comment by MohammedKaludi** [comment]
can you share more info about the issue, and can you share me the URL of that page?

**Comment by MohammedKaludi** [comment]
Github issues are for recreateable or bugs with info that can be replicated locally.

Closing the ticket due to lack of information on the issue.

Please contact 
https://ampforwp.com/support/ or https://wordpress.org/support/plugin/accelerated-mobile-pages/ 
if you need any assistances with the issue.
