### ISSUE TITLE
BUG: [ALSO IN PAGINATED CONTENT] When using AMPforWP + Yoast SEO the tag 'link rel=canonical' appears more than once in the document.

### ISSUE THREAD

**Issue by arleyandrada** [ahmedkaludi/accelerated-mobile-pages#4763]
The solution applied in issue #4696 did not solve the exact same problem in paginated content.

**Comment by Zabi09** [comment]
@arleyandrada I have checked the issue which you have reported but I am unable to recreate the issue on my end, Will you please provide me your website URL So that I can check once and let you know.

And the ticket which you have mentioned that user has not selected the Yoast option in the SEO section of the AMP plugin - https://prnt.sc/utaip4 and due to that, he was facing that error.

Have you selected Yoast in SEO option and if yes then please provide us your website URL where you have errors an I will check that once and let you know

**Comment by Zabi09** [comment]
@arleyandrada Can you please give us your website URL where you have errors?

**Comment by Zabi09** [comment]
Github is for recreatable issues, for technical support, please contact on site
