### ISSUE TITLE
PageBuilder fatal error - missing post carousel in ampforwp for Essential Addons 

### ISSUE THREAD

**Issue by nisiwi** [ahmedkaludi/accelerated-mobile-pages#4779]
Fatal error: Trait 'Essential_Addons_Elementor\Pro\Template\Content\Post_Carousel' not found in /home/ACCOUNT/public_html/wp-content/plugins/amp-pagebuilder-compatibility/widgets/essential-addon/amp-post-carousel.php on line 18

**Comment by Zabi09** [comment]
Sorry for the inconvenience, the issue which you are facing is due to the amp page builder compatibility plugin and not from the core AMPforWP plugin, So I have raised the ticket on our Trello board where we fixed all the extension related bugs and it will be fixed as soon as possible.

See this screenshot:
https://prnt.sc/uyb2qr
