### ISSUE TITLE
AMP Error Issues in Google Search Console

### ISSUE THREAD

**Issue by Empathyfine** [ahmedkaludi/accelerated-mobile-pages#4887]
Please how do I resolve the following four AMP Error issues as seen in my Google webmaster?

Error 1: Only amp-boilerplate and amp-custom 'style' tags are allowed, and only in the document head.

Error 2: Custom JavaScript is not allowed.

Error 3: Tag or text which is only allowed inside the body section found outside of the body section.

Error 4: Disallowed attribute or attribute value present in HTML tag.

Example of page with the error; https://www.fanslite.com/kendall-jenner-frank-ocean-take-ice-cream-ny-city/amp/

I am using "AMP for WP" - Accelerated Mobile Pages for WordPress By Ahmed Kaludi, Mohammed Kaludi

Meanwhile, below is the link to the JSON file of my AMP Export files which I have Exported; Please check it out and See how you can help me resolve the issue for me; Thanks!

https://www.dropbox.com/s/vf2og3bl9nkhcqv/redux_options_redux_builder_amp_backup_26-12-2020.json?dl=0

**Comment by Zabi09** [comment]
I have checked your issue by importing the settings on my end and found that you are adding the Google Ads in the wrong way and due to that you are having these errors - https://prnt.sc/wbcme5

Please remove the ad code which you have added in "Enter HTML in Head" and footer and after that, your errors will get fixed

And to add Adsense Ads in AMP please follow this tutorial - https://ampforwp.com/tutorials/article/how-to-add-advertisement-in-amp/

And if you need any help then let me know

**Comment by MohammedKaludi** [comment]
@Empathyfine Is your issue resolved?

**Comment by Empathyfine** [comment]
@Zabi09 and @MohammedKaludi thank you for your response, the recommendation helped!

My issues were resolved! Thank you for the help!

**Comment by Empathyfine** [comment]
Please how can I get more of my website pages indexed more with the AMP status.

I noticed that a friend who uses another AMP plugin gets his pages easily indexed with the AMP status, but not so with me using AMP for WP.

Please @Zabi09 and @MohammedKaludi what do you have to say about this?
