### ISSUE TITLE
Setting won't save

### ISSUE THREAD

**Issue by iamkingsleyf** [ahmedkaludi/accelerated-mobile-pages#4974]
Hi,

I have activated the plugin on 3 sites all wp 5.7 but the settings keeps popping up and asking me to choose beginner or advance mode

**Comment by Zabi09** [comment]
@iamkingsleyf if you click on it once then it will not appear again and it is strange to hear it from you, Are you using any plugin or theme which is having a redux framework? Will you please deactivate plugins temporarily and check once and let me know by which plugin/theme you are having this issue So that we can fix it.

**Comment by iamkingsleyf** [comment]
That is the shocking part of it, keeps appearing and the AMP menu is showing SETUP.
i tried it with BIMBER, Publisher by betterstudio, NEWSPAPER by tagdiv same problem

**Comment by Zabi09** [comment]
@iamkingsleyf will you please share the screenshot where you are seeing to set up in the AMP menu and have you tried deactivating plugins temporarily to check the setting not saving issue?

Please let us know

**Comment by Zabi09** [comment]
Pushed in 1.0.76.9
