### ISSUE TITLE
AMP plugin - php buffer issue

### ISSUE THREAD

**Issue by jlariza** [ahmedkaludi/accelerated-mobile-pages#5017]
Good day,

We are experiencing a strange issue. Some AMP pages were not returning any response. We started to check and it seems that php buffer memory died. We traced back the issue until this file:

`accelerated-mobile-pages/components/components-core.php:597` where there is a `echo $ampforwp_the_content;` . That echo was breaking the buffer if the page had a lot of content.

We had to reduce the page's content in order to make it work, but that is not the ideal approach.

I am wondering if the plugin is using and flushing correctly the php buffer. Has someone experienced something similar?

Thank you,

**Comment by Zabi09** [comment]
@jlariza Sorry for the inconvenience. I have added 50 paragraphs on one of our testing website - https://magazine3.com/garage/50-paragraphs-content-test/amp/ but did not get any error,

Will you please tell me exactly how many paragraphs you have on your website and also can you please share your content with us so that we can directly test it by adding your content on our end and you can send us the content with the help of this website - https://pastebin.com/

Please let us know

**Comment by jlariza** [comment]
@Zabi09 it is strange because the issue seems to be triggered by `<picture>` tags added by imagify plugin. It seems that the buffer breaks if the content is long and there are webp images.

**Comment by Zabi09** [comment]
@jlariza We have added the webp images by imagify plugin but we are still unable to recreate your issue - https://magazine3.com/garage/50-paragraphs-content-test/amp/ 

Will you please send us the content of WordPress editor with the help of this website - https://pastebin.com/ 

So that we can recreate it and then fix it

**Comment by HaripriyaHari** [comment]
Another user having the same issue: https://secure.helpscout.net/conversation/1509519999/195718?folderId=4195936

**Comment by HaripriyaHari** [comment]
Enable this "Display images in webp format on the site" option and generate again and check once and it will fix your issue for sure - https://www.awesomescreenshot.com/image/8397553?key=65a6df048811c7f47904c07eba025ae1

**Comment by Zabi09** [comment]
Github is for recreatable issues, for technical support, please contact on site
