### ISSUE TITLE
Needed to add the feature to limit Headline length to 110 characters only.

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5033]
Needed to add the feature to limit Headline length to 110 characters only.

help scout link - https://secure.helpscout.net/conversation/1520104268/197309?folderId=4459751

**Comment by DrAliRagab** [comment]
I think there is no need to limit `$post_title` to 110 characters, So the reader of the article can read the full title.
The issue appears with metadata array, so we can only limit `headline` to 110 characters.

```php
$headline_str = $post_title;

if (strlen($headline_str) > 110)
	$headline_str = substr($post_title,0,107) . '...';

$metadata = array(
	'@context' => 'http://schema.org',
	'@type' => 'BlogPosting',
	'mainEntityOfPage' => $this->get('canonical_url'),
	'publisher' => array(
		'@type' => 'Organization',
		'name' => $this->get('blog_name'),
	),
	'headline' => $headline_str,
	'author' => array(
		'@type' => 'Person',
		'name' => $post_author_name,
		'image' => $post_author_image,
	),
);
```

**Comment by DrAliRagab** [comment]
I will add the main issue here as a reference 

It's just a feature request for your awesome WP plugin.
Let's say I have a post with a title which is more than 110 characters.
Now if you try to test this page with https://search.google.com/test/rich-results you will get an error message that says " Not all markup is eligible for rich results", "invalid string length in field 'headline' ".
That's because according to google structured data type definitions https://developers.google.com/search/docs/data-types/article#structured-data-type-definitions , the headline string for AMP pages must not be more than 110 characters.

So I think it's better to add an option to limit Headline length to 110 characters only.

**Comment by DrAliRagab** [comment]
#5044

**Comment by Zabi09** [comment]
@DrAliRagab When I changed the $post_title directly then it was only changing the headline only and in the article, it was showing the full title only but anyways I have added the code which you have suggested which looks good thank you so much for that

**Comment by MohammedKaludi** [comment]
Ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.4 update
