### ISSUE TITLE
Blank White Page when linking to website in Facebook App for Android

### ISSUE THREAD

**Issue by gimmiefreebies** [ahmedkaludi/accelerated-mobile-pages#5075]
Hello, last Thursday my Facebook fans notified me that any links to my website, accessed through the Facebook app on Android, opened to a blank white page. In other words, links to my website were posted on Facebook. Fans using an Android device with the Facebook app tried to access my website links on Facebook app. Facebook app, by default, uses its own browser. My web page opened a blank, white page. I’m assuming it’s a Facebook app upgrade that caused this. I hadn’t changed anything on my website.

After troubleshooting for hours, I tried disabling the AMP WordPress plugin and voila! the links opened my website properly again. No more white screen of death.

My question: how can I have AMP enabled AND have Facebook properly open links to my website on the Facebook for Android app? I’d prefer to use amp because it helps page speed and ranking. But, a huge portion of my traffic comes from Facebook, so I can’t ignore that either.

If I had a handful of fans, I could ask them all to stop using Facebook app, or to start using “open website in browser”. But, my posts are seen by thousands of fans and that’s just not feasible. Thanks 🙂

Wendy
GimmieFreebies.com

**Comment by Zabi09** [comment]
@gimmiefreebies I have checked your website and found that you have removed the AMP on your website so I have checked it with the google cached version from search results of Google on mobile and found this URL - https://www.google.com/amp/s/www.gimmiefreebies.com/page/2/

Are you sure you were using our AMPforWP plugin? because I have checked your previous AMP design and it looks like you are using another AMP plugin and not our AMP plugin

Please let me know so that we can help you

**Comment by MohammedKaludi** [comment]
@gimmiefreebies  created the ticket on correct repo, so closing the ticket.
Also We have Facebook instant support built in with AMPforWP so if you ever want to use it we will be glad to have you.
