### ISSUE TITLE
Problem with SVG images

### ISSUE THREAD

**Issue by sanjaydadwani** [ahmedkaludi/accelerated-mobile-pages#5084]
SVG images are loading with a bigger size in the mobile version of the AMP website.
Ticket link -  https://secure.helpscout.net/conversation/1548585356/202784?folderId=4753923

AMP desktop preview: https://prnt.sc/188xkjp
AMP mobile preview: https://prnt.sc/188yzfu
Non-AMP desktop preview: https://prnt.sc/188ylsm
Non-AMP mobile preview: https://prnt.sc/188z630

**Comment by MohammedKaludi** [comment]
instead of `width:250` use `max-width:250`
if only width is used then it will enlarge the smaller svgs and that will create an issue.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3673cbd9a84d2db614ba884b7231ea7b1c3254d9#diff-c1b56bb9863011cdd850957569b8143c1486cf9ea2ccb85f5a305a6047005c4cR709

**Comment by MohammedKaludi** [comment]
height ko bhi max height kardo 
fix mar kardo

**Comment by Zabi09** [comment]
pushed in 1.0.77.11
