### ISSUE TITLE
Select Categories to Hide AMP posts Not working perfectly

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5152]
Reference Ticket URL: https://secure.helpscout.net/conversation/1666262891/215598?folderId=1060556

Created a category and hide it in AMP through **Select Categories to hide AMP post** this option.
The hide is working perfectly but to unhide that category, the category name is not showing.
Reference video: https://take.ms/om0Mo

A user scenario is different, the user added 2 categories to hide, and later he removed the category/unhide then the old post is not redirecting to AMP, and the new post redirecting perfectly.

**Comment by tripledm** [comment]
two years later and still having the same problem and you closed the ticket lol.. This problem I have on multiple installs all on different servers / environments.

**Comment by isrgrajan** [comment]
Try inspect element and see whether it is throwing any error on adding categories and saving the page

@MohammedKaludi @tripledm

**Comment by akshaywali** [comment]
As of AMPforWP 1.0.83 

1. Categories to Hide AMP posts option is working perfectly. 
**Note : If anyone still facing the issue then it most probably due to JavaScript  error due to some other plugin in backend**
2. Post not redirecting to  amp version when that post category was added to hide AMP and then removed. This issue was unable to recreate and post was redirecting as intended . 
**Note : Make sure you clear you cache if you facing this kind of issue since it can be caused to to server level cache**
