### ISSUE TITLE
Disqus comments iframe is not resizeable

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/accelerated-mobile-pages#5180]
Disqus comments iframe is not resizable, the comments are getting hidden because height is not changing based on iframe content.

Issue URL:- https://www.mondocalcioweb.it/2021/07/10/catania-calcio-attestata-lidoneita-delliscrizione-alla-serie-c-2021-2022/amp

Ref:- https://secure.helpscout.net/conversation/1721297696/219596?folderId=4874234

**Comment by Zabi09** [comment]
We have already fixed in issue here - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5055

Here is the option which we have added to select the layout fixed or responsive and also we can change the iframe height according to our requirement - https://prnt.sc/22puagr

So closing this ticket
