### ISSUE TITLE
AMP for WP Won't Allow Me To Change Settings. 

### ISSUE THREAD

**Issue by CONTXMedia** [ahmedkaludi/accelerated-mobile-pages#5211]
In both Basic Setup & Advanced the plugin will not allow me to change "Website Type, Where Do You Need AMP?, Design & Presentation, Analytics Tracking, Privacy Settings & 3rd Party Capability." 

Having previously used the plugin our original settings are stuck. 

I am a novice so any assistance will be greatly appreciated. 

Thanks.

**Comment by Zabi09** [comment]
@CONTXMedia Sorry for the inconvenience, Have you installed any new plugin on your website and then you started to see this error? Are you getting any errors on the console? and also are you using any plugin or theme which is having a redux framework? Will you please deactivate plugins temporarily and check once and let me know by which plugin/theme you are having this issue So that we can fix it.

**Comment by Zabi09** [comment]
Github is for tested and re-creatable bugs, for the technical issues, we will help you via website
