### ISSUE TITLE
Empty photo issue: WordPress gallery to AMP carousel

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#523]
The WordPress photo gallery gets every other photo space empty on AMP page. (Not showing photo1, photo2, and photo3 sequently. It shows photo1, empty, photo2, empty, and photo3)

Here is an example of AMP page.

http://redwinglife.com/amp-carousel-photo-gallery-test/amp/

I would appreciate if you could help me to resolve this issue.

Thank you for your help and support in advance.

REF: https://wordpress.org/support/topic/empty-photo-issue-wordpress-gallery-to-amp-carousel/

**Comment by Lofesa** [comment]
I think thi´s not a plugin issue but an amp for Automattic plugin issue. Your plugin don´t convert gallery to amp carousel, this work is done by the Automattic plugin.
The issue, I think, is that at some time a `<br />` is inyected between end tag of a image and the start of the next image (...`</amp-img><br/><amp-img`...) and these `<br/>` create empty `<div class="-amp-slide-item -amp-slide-item-show"><br class="amp-carousel-slide" aria-hidden="false"></div>` in the dom as you can inspect in chrome developers tools->elements.
And again, I think , that the issue is that in the [function](https://github.com/Automattic/amp-wp/blob/master/includes/embeds/class-amp-gallery-embed.php) that make the conversion, Automattic people add PHP_EOL between amp-img elements of carousel.
The test that must be made is change these PHP_EOL with a space ( ' ' ) and look if this do the trick and/or open an issue in the amp from Automattic plugin.
I can confirm that if you save all the html code in a file and delete these `<br/>` the carousel work fine.

**Comment by ahmedkaludi** [comment]
it's been a long time, not faced till then, closed.
