### ISSUE TITLE
Article content missing

### ISSUE THREAD

**Issue by Mellyod** [ahmedkaludi/accelerated-mobile-pages#5244]
AMP for WP - Accelerated Mobile Pages Plugin
The actual content for my articles in AMP version is missing. The example page is https://collectiblesandmoreinstore.com/marvel-figurine-collection/

The AMP version was also showing the featured image twice but I corrected that bug using css. But I can't have my article content blank. Please help. My email is maxcollector@aol.com. Thank you.

**Comment by Mellyod** [comment]
Now my content is missing on some of my pages. This is unacceptable. Example page: https://collectiblesandmoreinstore.com/about-our-collectibles-store/?amp

PLEASE can this be fixed PLEASE.

**Comment by Zabi09** [comment]
@Mellyod sorry for the inconvenience and will you please tell us how you are adding the content on your website? Are you using any page builder or creating a custom page template etc or you are using the WordPress editor - https://prnt.sc/6yS1zY1eQwL_ ?

If you are using the normal WordPress editor then the content will automatically appear in AMP but if you use a page template or any new page builder etc then we need to check it once and then help you.

Please let us know how you are adding the content so that we can guide you on the right path
