### ISSUE TITLE
Inline Styles not working correctly in Custom AMP Editor

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#533]
AMP is not showing the correct data entered in Custom AMP Editor.

ref: http://take.ms/OrC5r

http://take.ms/KOmOu

**Comment by loano** [comment]
I noticed that when I add some amp code to the Custom AMP Editor, it gets completely removed as soon as I save or jump from editor to visual.

**Comment by khaledMohammed000** [comment]
@loano yes the wyswig editor only accepts markup that is valid in wordpress, we will try to figure out a solution for this soon for AMP

**Comment by khaledMohammed000** [comment]
Hey @loano can you please update on this and is it expected behavior even with the actual WP editor?
also am curious as to what are your expectations regarding Custom AMP editor, like what it should do and what not?

It would really help if you answered these questions

**Comment by khaledMohammed000** [comment]
@loano is just AMP content getting stripped or all the content ??

**Comment by loano** [comment]
@khaledMohammed000 I just tested it again and it showed, that the only content which gets removed with the latest editor is amp code. The reason I'm using this is my video player. I did a lot of testing with different free players (Flowplayer, etc. ) over the last year and I come up with brid.tv as the best solution. In order to make their player available on AMP, I tried to add the code with the Custom AMP Editor. E.g.
<amp-brid-player data-partner="6997" data-player="8099" data-video="118707" layout="responsive" width="480" height="270"> </amp-brid-player>

**Comment by loano** [comment]
`<amp-brid-player data-partner="6997" data-player="8099" data-video="118707" layout="responsive" width="480" height="270"> </amp-brid-player>`

**Comment by khaledMohammed000** [comment]
one more question does the amp code for brit tv gets removed only when you switch ?

**Comment by loano** [comment]
Just tested it, its not working anymore. If I don't switch from text, the code stays in the field even when I publish the post, but there is no output on the frontend. When I set this up a month ago, it worked. All I did in the past was adding the following to your plugin:
`<script type="text/javascript" src="https://cdn.ampproject.org/v0/amp-brid-player-0.1.js" async="async" custom-element="amp-brid-player"></script>`

**Comment by ahmedkaludi** [comment]
This ticket was for inline styles, which seems to be fixed. Yet to be reviewed by @MohammedKaludi 

The Brid.tv support will be added but it's not a part of this ticket. So I am moving the issue to its original ticket #426 - otherwise It becomes hard to manage the code.

Thanks @loano for helping us improve the plugin! 

Regards,
Ahmed

**Comment by MohammedKaludi** [comment]
Working smoothly @khaledMohammed000 nice work.
