### ISSUE TITLE
amp-iframe not fully supported

### ISSUE THREAD

**Issue by danielcardoso5** [ahmedkaludi/accelerated-mobile-pages#534]
The resizable attribute on an iframe is not set in the converted amp-iframe. 
Also, setting the overflow and amp-img elements by AMP as in the docs here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md
is not supported.
This does not enable resizable iframes.

**Comment by nicholasgriffintn** [comment]
I think the reason there is no resizable attribute is because it is a pretty unique thing to need, sounds like something that would fall outside of the scope of a Wordpress plugin, however, that's simply my opinion on that.

I think that if this is something that you need to do them you might want to try coding it yourself, I doubt it's something that the majority of people using this plugin would want or need. That said, @ahmedkaludi and @MohammedKaludi would be able to answer that for you.

**Comment by ahmedkaludi** [comment]
@danielcardoso5 Thank you so much for helping us improve the plugin! Yes, like @nicholasgriffintn said, this is pretty unique challenge, but we will find out a creative solution to get working. I am pretty positive about this. I'm going to be working on the next update of the plugin in ticket #566 

So, I'll be closing this ticket. Please look out the developer in #566 and let's continue the discussion in that ticket.

**Comment by danielcardoso5** [comment]
@ahmedkaludi Thanks, I'll check the progress on the issue and I can help in testing the functionality.

**Comment by vlrevolution** [comment]
This issue is still present and keeping us from using amp-iframe. Please can you give me some advice on how to fix this? It is such a complex plugin and I am having a hard time figuring it out myself. We need resizable to work.

Maybe you can get some ideas from here:
https://github.com/ampproject/amp-wp/pull/4292/commits/c46532aad0070f36ed5bbc7918ecbd7a9c86f335#diff-3933722cc42f50f1ff2d283a331c7c98a77a26152cd1f42a36bde5562adf129b
