### ISSUE TITLE
AdSense ads do not load in AMP.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5341]
Ref:- https://magazine3.in/conversation/70344?folder_id=21

**Comment by Sanjeevsetu** [comment]
Waiting for user's reply

**Comment by isrgrajan** [comment]
This maybe due to cache issues or conflict with any plugin that you maybe using. You can follow the following steps to diagnose the issue:

- If you're using a cache plugin, use the "pure cache" option or disable the plugin.
- Turn off any minifying plugins you're using.
- If you use Cloudflare, then enable development mode.
- Open your website in incognito or private mode, then inspect elements to see if there are any errors in the console.
- Keep in mind that it is Google's decision whether or not to display ads on a specific page, and this takes time in the case of new ad units.

**Comment by Sanjeevsetu** [comment]
Hi @isrgrajan 

Yes, you are right here. It may be due to cache issues because the ad is now being displayed for that user. I am closing this ticket.
