### ISSUE TITLE
View non-amp and Leave a comment not working 

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5404]
When there is mobile redirection enabled, View non-amp and Leave a comment is not working in amp version in mobile.

Note-: User specific issue

Reference ticket -: https://magazine3.in/conversation/106163?folder_id=23

**Comment by muslimakhan** [comment]
@77naveenop , As we discussed this issue is on mobile device, redirection not working, I give whole half day on it and found it is not an issue because when we select in AMP Settings -> Advanced Settings -> Mobile Redirection ON then it would be happened in mobile devices, please check screenshot: 

https://prnt.sc/b0bj6QQJKM5c
