### ISSUE TITLE
KK star rating and other rating support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#571]
KK star rating and other rating support

**Comment by MohammedKaludi** [comment]
Already fixed in : https://github.com/ahmedkaludi/amp-rating/commit/ab172762323808af62bb2c16e0cecc1fd34e195f

https://github.com/ahmedkaludi/amp-rating/commit/fac59bede91eaa71e0c7ab71a293ef46dcef3294

https://github.com/ahmedkaludi/amp-rating/commit/d5e125a0e74984f108390a417d2a22bae50f4ce5

and 

https://github.com/ahmedkaludi/amp-rating/commit/43bf5681c14446930df84095a8de4a1c7a0a5198
