### ISSUE TITLE
We need to change Featured image aspect ration in design 2 and 3

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#581]
It should be like Design 1.
In design 2 and 3, it's getting stretched or squeezed.

ref: https://masterinvestor.co.uk/equities/this-company-wants-to-make-investing-great-again/amp/

**Comment by foliovision** [comment]
We are still having this issue with design 3.

For image which is 828x1104 px the resulting HTML is:

`<amp-img layout="responsive" width="450" height="270" ...></amp-img>`

Notice the badly calculated width and height. That results in a deformed image.

Thanks,
Martin

**Comment by foliovision** [comment]
I checked accelerated-mobile-pages/templates/design-manager/design-3/index.php and realized that's where he issue starts, it just takes `medium_large` size and assumes size 450x270 for it: https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/design-manager/design-3/index.php#L65-L72 Well that one is for the slider, there is similar code down below for the thumbnails on homepage.

Shouldn't there be instead of setting to allow people to pick any of their defined image sizes?

I wanted to fix this by creating a local copy of the theme as described here: https://ampforwp.com/tutorials/article/activate-amp-theme-framework/ But then my new theme was just a list of post thumbnails and titles and all the styling and sliding carouse of featured posts was gone.

So I had to adjust your plugin directly and block updates to it.
