### ISSUE TITLE
Twitter embeds

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#584]
ref: https://wordpress.org/support/topic/design-3-issue-in-the-footer/

**Comment by ahmedkaludi** [comment]
The twitter embeds already works with our current version. It's just that the twitter embed js is not included that's why it automatically displays the tweet in blockquote, if that js is available then it displays in a very nice way.

We need an option in the Single section which allows users to turn on the native twitter embed support which will make this js to appear only in the single of all the designs. By default, this option should be off.

**Comment by ahmedkaludi** [comment]
I have tested it with twitter embeds and they are working perfectly fine.
