### ISSUE TITLE
https is required for audio & video uploads

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#591]
Users dont know that https is required for audio and video embeds.
How can we solve this?

ref: http://take.ms/S22Om
http://www.limacharlienews.com/mena/breaking-explosions-gunfire-istanbul/amp/

**Comment by Lofesa** [comment]
Same as with search. Option in options panel, if enabled, convert these tags in https,if disabled strip the embed. And a big,big, very big, mesage that ssl is needed to the source of video/audio

**Comment by nicholasgriffintn** [comment]
Yes, that is an AMP requirement of the script, you need to move your site to HTTPS.

You should do this anyway because it actually makes things faster and a lot faster, sign up to Cloudflare if you haven't already and get on their HTTPS service, it's awesome, and CloudFlare adds so much on top of that too, and it's free.

You can find out more about Cloudflare's SSL here:

https://blog.cloudflare.com/introducing-universal-ssl/

**Comment by ahmedkaludi** [comment]
Hey @Lofesa 

Yes, that's a good idea. Atleast it doesn't gives validation issues.

Let me discuss that with my team

**Comment by ahmedkaludi** [comment]
We need to create a tutorial on this. That's the only possible solution in my opinion.
