### ISSUE TITLE
href is not allowed in div

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#635]
ref: http://pastebin.com/uv5mgy61

screenshot: http://take.ms/4PhSW

**Comment by nicholasgriffintn** [comment]
well no, you should have a href in a div normally, that's not valid html.

**Comment by khaledMohammed000** [comment]
this issue is being dropped as there are several other alternative plugins available for use that have followed standards, 

if you still insist on using the above plugin here is code snippet you can add in features.php in function "ampforwp_the_content_filter" and still use the FB like button

`// removing attribute href and width from divs
// for html code go here for testing : http://pastebin.com/ZBwEJsQ8
$dom = new DOMDocument;
$dom->loadHTML($content);
$divs = $dom->getElementsByTagName('div');
		foreach ($divs as $div) {
				$div->removeAttribute('href');
				$div->removeAttribute('width');
		}
$content = $dom->saveHTML();`

**Comment by MohammedKaludi** [comment]
@ahmedkaludi  Please take a look at this ticket as this has nothing for development

**Comment by ahmedkaludi** [comment]
Sure, Agreed @MohammedKaludi I'll close this
