### ISSUE TITLE
Rendering the wrong URLs in front page if paged 

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#742]
Static front page rel canonical and amphtml.

Ref:  https://secure.helpscout.net/conversation/338347252/11634/?folderId=1060551

Ref: https://monosnap.com/file/PhJXHusEO1wO0qwaVqYjQBiPptnVsX

**Comment by kavirus** [comment]
The way I solved this issue was by modifying the line **157** from the **features.php** file (https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php)

The if statement needs to consider the is_home (which is doing it) but also is_front_page, resulting in the following line of code:

_**if ( (is_home() && $wp->query_vars['paged'] >= '2') || ( is_front_page() && $wp->query_vars['paged'] >= '2') ) {**_

Hopefully this will help others with the same issue.

**Comment by khaledMohammed000** [comment]
Need some discussion on this and then we can complete this ticket

**Comment by khaledMohammed000** [comment]
The decision was taken to add rel="canonical" for paged pages of front page....
With regards to rel="amphtml" for paged pages of front page we are not sure of the content that will be used in front page sofor now we are not going to add rel="amphtml" on pages front pageon non amp website

**Comment by MohammedKaludi** [comment]
Seems fixed did some extensive testing and looking good so far.
