### ISSUE TITLE
Widgetized sidebar with AMP-sidebar 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#76]
Check out this interesting thread from Alex: https://wordpress.org/support/topic/wordpress-right-side-bar-not-displayed/

**Comment by nicholasgriffintn** [comment]
That could be interesting, it would be cool to have a custom HTML box for additions, however, due to AMP being AMP, this might have to be regulated a bit, maybe providing options for additions with some customisation, rather than full customisation.

For example, it's definitely possible to add other links, but you don't want the user to set them themselves, needs to be a checkbox, and just the URL entry kind of thing.

**Comment by ahmedkaludi** [comment]
We didn't receive much excitement about this.. we do have a new widget area on homepages though. we're closing this one to stay focused
