### ISSUE TITLE
Test titles with The SEO Framework Plugin

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#760]
Test titles with The SEO Framework Plugin

Ref: https://wordpress.org/support/topic/strange-seo-yoast-or-die/

**Comment by sybrew** [comment]
The issue is that it actually removes WordPress legacy code within function `ampforwp_remove_title_tags()`.

Instead, you should filter `wp_get_document_title()`:
https://github.com/Automattic/amp-wp/blob/22b8287c8a84f774f73942c3c08027ddad3f1e0d/includes/class-amp-post-template.php#L52

Stack:
1. https://developer.wordpress.org/reference/functions/wp_get_document_title/
2. Filter `pre_get_document_title` at priority 10.
3. Run `ampforwp_add_custom_title_tag()` in the title.

I'll send a PR. Be sure to test it out before including it, both with legacy settings and in combination with SEO plugins (Yoast/AIO/TSF/etc.).

**Comment by khaledMohammed000** [comment]
Hey @sybrew thanx for the info and also for the commit, will check the PR thoroughly 👍

**Comment by sybrew** [comment]
Done & done! 😄 

FYI: It's still untested. 😅
