### ISSUE TITLE
Compatibility with Newspaper theme by Tagdiv

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#796]
With this theme enabled, categories showing only 2 posts not more than that.

https://secure.helpscout.net/conversation/342132654/11811/?folderId=1060551

**Comment by jfthai2015** [comment]
Hi Marqas, just to correct you as I think you slightly misunderstood the issue.

I changed the layout since then on the production website so this issue doesn't trigger anymore, but the issue can be seen in the staging environment, where you'll be able to see that the first 3 posts of ANY CATEGORY are **consistently skipped** in the amp version

Here you are:

**Reminder : USE ONLY MOBILE VIEW**

see the difference of posts between this : https://mgn.ikanaweb.com/loisirs/photo/

and this : https://mgn.ikanaweb.com/loisirs/photo/amp

**Comment by MARQAS** [comment]
@jfthai2015 since you have changed the layout, are you still in need of this fix? You are the only one with this issue, if you don't need it anymore, I'll close this ticket

**Comment by jfthai2015** [comment]
Hi Marqas, as I already said before.
Being the only one to notice and report an issue doesn't means I'm the only one having it.
Your plugin is clearly not fully compatible with Newspaper.
Here's the first three articles of the Newspapers mobile theme category pages : http://prntscr.com/f0wj05
The tagdiv's mobile theme always shows the first 3 articles like that

Here's your same amp page: http://prntscr.com/f0wiva

**Comment by jfthai2015** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/842

As I said, being the first or only person to report an issue doesn't mean you're the only person having the issue.
You're just the only person reporting it, because having noticed it
