### ISSUE TITLE
Google error message: Problem with URL protocol "http:"

### ISSUE THREAD

**Issue by NilsHoyer** [ahmedkaludi/accelerated-mobile-pages#913]
I've got a notification from Google about a problem on my server:
> The URL protocol "http:" of the attribute "action" in the tag "FORM [method=GET] is invalid

The html code of that page contains:
`<form role="search" method="get" id="searchform" class="searchform" target="_top" action="http://nils-weg.de">`

The URL of this page is: http://nils-weg.de/amp

Is this a wrong configuration from me or is this a problem inside your code?

PS
For my last issue, I offered a Pull request to you - but you didn't apply it. So today I will not try to find a solution for your code...

**Comment by MohammedKaludi** [comment]
Hey @NilsHoyer 
The warning you are getting from Google is because your URL is not https, but we have found the workaround and fixed it in the update which we are planning to release in next few hours.

Check out this reference ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/912

And please don't get mad over pull request not getting merged, we are literally bombarded with the queries, it is very hard for a small team like ours to give justice to all the requests. Also, your PR was not neglected but it was scheduled and was going to look into the related PR's when I come to fix the issues. Your PR is related to Debug issues so I have added the reference in the ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/859

Once I start working on the fix I will look into the PR's and hopefully merge it into the code. I hope you will understand that we never ever take the help as granted and I will really be happy to see your contribution to this project, more Pull requests in future and make this plugin more awesome.

Thank you,
Mohammed Kaludi
